### ISSUE TITLE
Bizom - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#119]
1. /on_search:
- time.timestamp for "enable" needs to match Context.timestamp;
- time.schedule.holidays is mandatory key (can be empty array);
- time.range.end of "2400" is invalid time (can be "2359");
2. /on_status:
- pickup time (fulfillment.start.time.timestamp) and delivery time (fulfillment.end.time.timestamp) are mandatory as per the contract;
3. /on_update1:
- quote adjustment & refund doesn't happen in "return initiated" state;
4. /on_update2:
- quote adjustment & refund  doesn't happen in "return approved" state;

**Comment by BLR-0118** [comment]
@samarthpatel-bizom

**Comment by samarthpatel-bizom** [comment]
For "quote adjustment & refund doesn't happen in "return initiated" state": 
 -> Does that mean we are supposed to send the same quote including the items under return_initiated/ return_approved state ? And if the return is liquidated we can send the updated quote which BAP will consume and process refund ?
 
@BLR-0118 can you please validate whether my understanding is correct or not ?

**Comment by samarthpatel-bizom** [comment]
Also please clarify whether all the flows needed to be resubmitted or a single flow will be enough ?

**Comment by BLR-0118** [comment]
There are specific states set by the seller at which the buyer app will trigger the refund (this is clearly documented in the API contract doc). It's only in these states that the quote adjustment should happen.

**Comment by samarthpatel-bizom** [comment]
Yes understood and have raised the PR accordingly: https://github.com/ONDC-Official/v1.1.0-logs/pull/121
Thanks

**Comment by BLR-0118** [comment]
@samarthpatel-bizom

**Comment by samarthpatel-bizom** [comment]
1. Acknowledged
2. The on_status was of the older order for which we were not sharing timestamp.
3. Acknowledged: reusing same message id from /update.

Thanks.

@BLR-0118

**Comment by BLR-0118** [comment]
logs cleared for v.1.1.0
