### ISSUE TITLE
eVitalRx - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#157]
Flow 1
====
1. /on_search:
- bpp/providers.time.label - valid values are "enable", "disable". You should use this to enable or disable stores;
- item.quantity.available.count and maximum.count are string as per contract;
- item.price.value & item.price.maximum_value are string;
- for serviceability: type="12" (means pan-India), val should be "IND" and unit "country";
- fulfillments.contact.phone should be 10 or 11 digit numeric only (no "+");
- item.id encoding is based on hashed or encrypted val? This may create problems with signing.
2. /select:
- provider.id & location.id are different from what came in /on_search but item.id is the same. How?
3. /on_init:
- quote.breakup should have both total price & unit price (as in /on_select);
- buyer_app_finder_fee_type should be "percent" (lower "p");
- in payment block, remove everything except buyer_app_finder_fee_type, buyer_app_finder_fee_amount, settlement_details;
4. /on_confirm:
- remove order.documents which has invoice and add to /on_status when fulfillment state changes to "Order-picked-up";
5. /on_status:
- using same message_id as /confirm;
- billing.updated_at should not change;
- price.value, params.amount should be string;
- remove settlement_basis, settlement_window;
6. /on_status2:
- same issues as for /on_status above;
- fulfillment.start.time.timestamp should be set when fulfillment state becomes "Order-picked-up" and fulfillment.end.time.timestamp should be set when fulfillment state becomes "Order-delivered";
7. /on_update:
- item.quantity.count should not become 0 when status is "Return_Initiated";
- you should have another unsolicited /on_update call where status is "Liquidated" and here item.quantity.count and item_quantity becomes 0 (use the same message_id here as in /update);
- quote has 2 items but items has only 1 (it should have both these items);
- fulfillments is empty array but fulfillment_id is referenced in items. Details of fulfillment "F1" should be in fulfillments;

Flow 3
====
- same issue in /on_update as in flow 1;

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by evital-manav** [comment]
/on_select 
did not get this point.

**Comment by BLR-0118** [comment]
/on_search: for 10km radius, use type="10" (for radius based serviceability), val="10" (for 10 km as defined by unit), unit="km";
.on_select - there's nothing for /on_select but /select. why has the provider id & location id changed between on_search & select for the same items (as identified by the id);

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by evital-manav** [comment]
/select is with the same provider_id and same location_id, and 2 items are different.

5. /on_status messsage_id should be different right?

**Comment by evital-manav** [comment]
/on_update:

4. fulfillment details still be needed for liquidated returns? @BLR-0118

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by BLR-0118** [comment]
Flow 3
====
1. /on_update, /on_update2: changes should be consistent with what's mentioned for Flow 1 above;

**Comment by BLR-0118** [comment]
@evital-manav

**Comment by evital-manav** [comment]
Flow 1: 
/on_search the sellers we connect are more into hyperlocal, that's why we kept it as radius based. the 100 km radius I had added in the staging for testing. will change it to below 5km.

**Comment by evital-manav** [comment]
/on_update:
2nd entry in order.items array should be removed;

It should be removed, because it is 0?

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_status, /on_status2, /on_status3:
- delivery charge of 50 in /on_confirm is 0 here. why?

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0
