### ISSUE TITLE
Plotch Seller App - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#23]
Flow 1:
1. No /on_select, hence can't verify fulfillment TAT promised;
2. /on_confirm:
- fulfillment.start.location (descriptor, id, gps) are different from what's in /on_search. This should be the same since the pickup location is the same as the provider location in /on_search;
- fulfillment.rateable not available;
4. /on_status_ready_for_pickup_flow1 - fulfillment id is "01" while in earlier APIs (like /on_init), it's "1";
5. /on_status_dispatched_flow1:
- fulfillment.start.timestamp > Context.timestamp (can't be future dated);
- payment.uri is different from what's in /on_confirm;
- payment.params.transaction_id missing;
6. /on_status_delivered_flow1:
- same issues as 5 above;
7. /on_update_return_initiated:
- not sure how fulfillment category is "Immediate Delivery"?
- flow for return with reverse QC follows: return initiated -> return approved -> return picked -> return delivered and reverse qc fulfillment is initiated at "return approved";
- other states should be sent with /on_update (with the same message id as /update to handle an issue with current API where individual return requests can't be tracked otherwise)

**Comment by BLR-0118** [comment]
Flow 2:
1. /on_init (serviceability issue) - payload needs to be as per contract (check under /on_select);
Flow 3:
1. /on_update (return rejected) - shows for return status "return initiated" instead of "return rejected";
Flow 5:
- can you pls share /on_status after cancel?

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
All feedback implemented @BLR-0118  
Please review https://github.com/ONDC-Official/v1.1.0-logs/pull/44

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- holidays is mandatory, can be empty;
2. /on_init:
- payment: should only have finder fee type, amount, settlement details;
3. /on_status_dispatched:
- pickup time (fulfillment.start.time.timestamp) is same as Context.timestamp for /confirm. How? This should be set to the actual pickup time;
- delivery time (fulfillment.end.time.timestamp) is same as Context.timestamp for /on_confirm. How?
4. return with reverse QC: why is this not shown through /on_update (preferably with same message_id as the original /update for now);

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
@BLR-0118 Feedback implemented. https://github.com/ONDC-Official/v1.1.0-logs/pull/62

**Comment by BLR-0118** [comment]
1. Catalog should comply with this [spec](https://docs.google.com/document/d/1E6CxPuFSmh9VMW-Ky9z0tF1EuZfWW2wgwBRTkDE_74k/edit#);
2. For /on_update, can you pls share the /update & /confirm payload so it's clear what's being returned?

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
@BLR-0118  on_search payload verified and corrected with spec shared. 
Added update and confirm payload for the provided transaction ID. 
https://github.com/ONDC-Official/v1.1.0-logs/pull/115

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0
