### ISSUE TITLE
Innobits - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#26]
1. Retail  Seller App:
- logs need to be submitted for all flows in the test case scenarios [here](https://docs.google.com/document/d/1ttixilM-I6dutEdHL10uzqRFd8RcJlEO_9wBUijtdDc/edit);

**Comment by BLR-0118** [comment]
for all APIs:
- billing.created_at & updated_at are defined by buyer app in /init and should remain same all thru;
- order.created.at is defined by buyer app in /confirm and will remain same all thru but updated_at will be updated wherever order / fulfillment states are changed;

**Comment by BLR-0118** [comment]
@darshansada604

**Comment by BLR-0118** [comment]
@darshansada604 - I noticed from Phonepe logs that in the quote, you're not sending both total price & unit price for title_type of "item". Pls have this fixed also.

**Comment by darshansada604** [comment]
@BLR-0118 "value":
        {
          "currency":"INR",
          "value":"50000"
        }
this is there in v 1.0 and v1.1.0 and the same we've sent not sure why intent.value is invalid

**Comment by darshansada604** [comment]
@BLR-0118 also help us how to provide logs as per the test cases scenarios as buyer app preprod does not support part cancel/ part returns i also reported to abhinandan, phonepe preprod app also is not there with us and also they don't support part return/ part cancel.
we wont be able to provide logs unless this is supported!

**Comment by BLR-0118** [comment]
Logistics buyer app (logs with Dunzo):
1. [/search](https://github.com/ONDC-Official/v1.1.0-logs/blob/main/Dunzo/Dunzo-Innobits/Flow_1/search.json):
- Context.ttl should be "PT30S" for all APIs;
- start.location.id & end.location.id isn't a part of contract & can't be the same;
2. [/confirm](https://github.com/ONDC-Official/v1.1.0-logs/blob/main/Dunzo/Dunzo-Innobits/Flow_1/confirm.json) - billing address is different from [/init](https://github.com/ONDC-Official/v1.1.0-logs/blob/main/Dunzo/Dunzo-Innobits/Flow_1/init.json); billing address should be for the seller marketplace, hence, /confirm address looks correct;
3. /confirm - created_at & updated_at are for order, not "@ondc/org/linked_order". This key is invalid;

**Comment by BLR-0118** [comment]
@darshansada604

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- provider.time.timestamp for enabling/disabling merchant must match Context.timestamp;
- pls use one of the non-deprecated categories from this [list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0). In your case, it would be "Oil & Ghee" instead of "Packaged Foods". This is the same list of categories which is supported by all buyer apps today;
- serviceability needs the category name ("*" is not supported);
- time.schedule.holidays is mandatory (empty array ok);

2. /on_init:
- in payment block, only keep finder fee type & amount, settlement_details;

3. /on_confirm:
- order.updated_at should be updated as default fulfillment state added;

4. /on_status2:
- order.created_at timestamp changed from what's set in /confirm. This is incorrect;

5. /on_status4:
- order picked up means pickup time should also be provided (fulfillment.start.time.timestamp);

6. /on_status5:
- order delivered means both pickup & delivery time (fulfillment.end.time.timestamp) is mandatory;

Flow 3
====
1. /on_update:
- should have same message_id as /update;
- if return is rejected, why is quote.price.value = 0 and why is reverse qc fulfillment initiated?

Flow 4
====
1. item out of stock payload not available

**Comment by BLR-0118** [comment]
@darshansada604

**Comment by darshansada604** [comment]
@BLR-0118 but we did not receive this from logistics, hence it was not passed, you check our logistics on_status logs from LSN as well

**Comment by BLR-0118** [comment]
1. /on_search:
- "Packaged Foods" is a deprecated category and shouldn't be used. Only the non-deprecated categories (not highlighted) in this [list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0) should be used and the keys should be mapped in the corresponding struct identified here;
- item.descriptor.code needs to be in the format as per the API contract;
- item.brand_owner_FSSAI_license_no is not a valid key, it should be inside "@ondc/org/statutory_reqs_packaged_commodities";
- contact_details_consumer_care should be in this format (as per API contract): "name,email,contactno";
- serviceability: category "Grocery" is invalid, pls use the correct category from this [list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0);

Flow 1
====
2. /on_init, /on_confirm, /on_status, etc.:
- for title type "item", quote.breakup for that item should have total price & unit price;
- why does /on_select have it but not these other APIs when they map to the same order quote?

Flow 3
====
1. /on_update:
- if return is rejected, order value (quote.price) should remain the same as before. Why has it changed here?

**Comment by BLR-0118** [comment]
@darshansada604

**Comment by BLR-0118** [comment]
1. /on_search (these may be because of preprod; if so, pls confirm)
- Most items (such as ghee, etc.) is mapped as beverage instead of "Oil & Ghee" or similar categories?
- for item id 7122 & 9162 & few others, category_id is ""Beverages"" (2 double quotes which is syntactically invalid);
- item.descriptor.code for all is the same "1:0066";
- serviceability construct is defined only for "Beverages". Why not for some of the other categories used "Beauty & Hygiene", "Snacks & Branded Foods", etc.?

2. /on_select, /on_init:
- item.quantity.available.count & item.quantity.maximum.count are string (as per API contract);

**Comment by darshansada604** [comment]
@BLR-0118 1. on_Search all these are because of pre-prod, on prod we have rich data mapped to corresponding categories as per the contract

will change the datatype for this item.quantity.available.count & item.quantity.maximum.count are string and submit it in few mins

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0
