### ISSUE TITLE
DTDC - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.1.0-logs#274]
## Flow 1 (Delivered Flow)

**/search** (Mytra Money)

- either of the split timings or fixed timings (both time and frequency) should be provided in /provider (LSP should have sent NACK)
- dimensions are required for P2H2P shipments (LSP should have sent NACK)

**/on_search**

- /message/catalog/bpp/providers/items/time must have required property 'timestamp' (refers to the date & time for which duration is provided)

**/on_init**

- delivery charges should be inclusive of tax
- settlement_counterparty should be 'seller app' in @ondc/org/settlement_details as payment is collected by BAP

**/on_update**

- why has order/state changed to 'In-progress'
- @ondc/org/linked_order and billing object are not required

**/on_status**

- name is not required in /order/state/descriptor/code
- pickup time (fulfillments/start/time/timestamp) should match context.timestamp for fulfillment state 'Order-picked-up'
- order.created_at and order.updated_at should be provided
- billing object mismatch between /init and /on_status (created_at and updated_at missing)
- message_id should be a string for /on_status_delivered and /on_status_agent_assigned
- delivery time (fulfillments/end/time/timestamp) should match context.timestamp for fulfillment state 'Order-delivered'

## Flow 2 (Cancellation Flow)

- similar issues as Flow 1

**/on_cancel** 

- flow for unsolicited cancellation by the seller should be provided

@aditya-sharma2-shipsy

**Comment by tanya-ondc** [comment]
## Flow 1 (Delivered Flow)

**/on_search**
- context/city mismatch with /search.

**Comment by aditya-sharma2-shipsy** [comment]
@tanya-ondc  Can you please share if this is mentioned somewhere as per the protocol, because we have provided this city value as per the city in which we are serviceable and the city value that we have subscribed

**Comment by tanya-ondc** [comment]
@aditya-sharma2-shipsy The city code (for all subsequent API calls) should be same as city code in /search call.
Also, I see that the city code in /on_init and /on_confirm is same as the one in /search. The issue is only in /on_search.

Kindly rectify this and resubmit the logs. Will perform final review.

**Comment by aditya-sharma2-shipsy** [comment]
@tanya-ondc  We have made the fix and have done one new round of testing and have created new logs and have raised a PR for the same
below is the attached PR for the same 
https://github.com/ONDC-Official/v1.1.0-logs/pull/299

Request you to please review our logs

**Comment by bluecypher** [comment]
- Please share unmodified/unprocessed logs from buyer app side

**/on_search**

- As per the duration P2D = 48 hours (B2C SMART EXPRESS), the timestamp should be of the date 21/06
- Express Delivery should be used instead of Standard Delivery (Premium) (can't deliver P2H2P by surface in 1 Day)

**/on_confirm**

- Invalid length of AWB no. in @ondc/org/awb_no (should be a valid 11-16 digits no.)

**/on_status**

- pickup/delivery timestamp must be earlier than order/updated_at timestamp

**/on_update**

-  start of the pickup/delivery timestamp ranges can't precede context/timestamp


@aditya-sharma2-shipsy

**Comment by bluecypher** [comment]
- prices should be dynamically calculated in /on_search (please avoid placeholder values)
- /on_status: fulfillments//type should be "Prepaid" (instead of "PREPAID")

@aditya-sharma2-shipsy

**Comment by aditya-sharma2-shipsy** [comment]
@bluecypher we have made the changes as per your comment and have created new logs after testing
as per about the dynamic pricing, the prices are dynamic based on the master which we have for pricing, which we configure based on our branches, for now we have set the  pricing values as per just to branches hence you see the price repeating, the price u see is also calculated based on the internal logic and will completely be different from Production pricing

**Comment by bluecypher** [comment]
@BLR-0118, the logs seem fine, pls proceed with your review.


@aditya-sharma2-shipsy, the delivery with longer TAT has a higher price. Is this intentional?

**Comment by aditya-sharma2-shipsy** [comment]
@bluecypher As I have mentioned that these prices are completely dummy and are not provided by our business Team, we will be showcasing the actual pricing on Production and these prices are completely dynamic.
Just for testing purpose we have input such price and was just a overlook that we had put a higher price for a service with lower TAT
but these all things will be completely as per our business process on Production.
