### ISSUE TITLE
nStore - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#31]
Logistics buyer app - logs with Delhivery:
1. [/confirm](https://github.com/ONDC-Official/v1.1.0-logs/blob/main/Delhivery/Delhivery-nStore/confirm.json) - start.person.name is mandatory;

**Comment by BLR-0118** [comment]
@arunraj-nstore

**Comment by BLR-0118** [comment]
Logs with Shiprocket:
1. [/confirm](https://github.com/ONDC-Official/v1.1.0-logs/blob/main/Shiprocket/Shiprocket-Nstore/Delivered_Flow/confirm.json) - "@ondc/org/linked_order".item.quantity.count should be integer;

**Comment by BLR-0118** [comment]
@arunraj-nstore

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- for F&B, pls use category "F&B" for now;
2. /confirm & /on_confirm:
- order.state should be "Created" in /confirm and "Created" or "Accepted" in /on_confirm. In the logs, it' the reverse which is incorrect;
3. /on_status:
- for item "238" & 241, item.price.value * item.quantity != price.value;
- payment.params.transaction_id was not null in /on_confirm, but null here;
4. /on_update_return:
- quote adjustment and refund is not initiated at "return initiated";
- payload is incorrect;

Flow 2
====
1. /on_init_non_serviceable:
- payload is incorrect, needs the complete response as shown in the API contract doc (under /on_select);

Flow 3
====
1. /on_update_return_rejected:
- payload is incorrect;

Flow 4
====
1. item "out of stock" payload not available

**Comment by BLR-0118** [comment]
@nstoretech

**Comment by Girisuta** [comment]
F&B, pls use category "F&B" for now - How abour Home & Decor ? 

for item "238" & 241, item.price.value * item.quantity != price.value; - We send the item.price.value - excluding tax , and we send the price.value  inclusive of tax. Please clarify how do we send ?

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_status_1:
- quote.price.value is not adding up to quote.breakup[].price.value;
- for item "101", total price is not equal to item price * qty;
2. /on_update1, /on_update2: pls check the flows from Shopalyst logs;

Flow 2
====
1. /on_init_1:
- since fulfillment is non-serviceable, there can't be any fulfillment level charges (like "misc");

Flow 4
====
1. No item out of stock payload ?

**Comment by BLR-0118** [comment]
@nstoretech

**Comment by Girisuta** [comment]
@BLR-0118  We have sent out of stock in Flow 5 
For Flow 4 - as per the use case, we proceed with the existing count

**Comment by Girisuta** [comment]
@BLR-0118  in the yesterday's logs , we have verified and fixed the following : /on_status_1:
quote.price.value is not adding up to quote.breakup[].price.value;
for item "101", total price is not equal to item price * qty;
/on_update1, /on_update2: We have compared with Shopalyst 
/on_init_1:
since fulfillment is non-serviceable, there can't be any fulfillment level charges (like "misc"); - When it is non serviceabile, misc charges removed 
Flow 4 has - Non Serviceable in On-Init 1 , out of stock in on_select . 
Kindly review .

**Comment by BLR-0118** [comment]
1. /on_status:
- billing.updated_at can't be changed by seller NP;
2. /on_update, /on_update.1:
- payload is invalid;
- quote should be updated only at the payment trigger point (e.g. "Liquidated");
- For /on_update.1, Context.message_id should be the same as /update (temporarily as there's no other way to track the specific return request);

Flow 2
====
- non-serviceable use case not handled;

Flow 3
====
Return reject payload is invalid;

No payload for flow 5?

**Comment by BLR-0118** [comment]
@nstoretech

**Comment by bluecypher** [comment]
## Flow 1

**/on_status**

- order.created_at should remain the same as /confirm timestamp

## Flow 2

**/on_select**

- Non-serviceable use case is not handled

## Flow 3

**/on_status**

- context.city can't change in /on_status
- order.updated_at should match context.timestamp

**/on_update (return rejected)**

- reverse qc fulfillment should not be created when return is rejected


@nstoretech

**Comment by Girisuta** [comment]
Flow 2
/on_select
Non-serviceable use case is not handled 

As discussed with @BLR-0118 , for Non-Serviceable, it can be either are /on_select or /on_init. on the buyer app, we were able to change the address only during init . Looks like one more on_init is missing .. is it ok to upload Flow 2 & Flow 3 alone again ? 
Kindly confirm @BLR-0118

**Comment by Girisuta** [comment]
@BLR-0118 : Please confirm : 

1. order.updated_at should match context.timestamp - We send the updated time from our DB for  order.updated_at which has a difference of 1 sec compared to context.timestamp as we send the status after the data gets updated in DB. Please clarify if this is not correct.

**Comment by BLR-0118** [comment]
Where are the logs for search? Pls share the last search response sent to this buyer app using which other test cases here are executed

**Comment by BLR-0118** [comment]
@nstoretech

**Comment by sathiamour** [comment]
> Where are the logs for search? Pls share the last search response sent to this buyer app using which other test cases here are executed
@BLR-0118 
We did not get search request from plotch apps , as suggested by @vikramacharya we used [](https://ondc.indiastack.cloud/seller/20971) to get the products. We executed the flow 5 from reference buyer app where we got the search request and the logs have been given for the search as part of flow 5. Other flows were executed from plotch app.

**Comment by BLR-0118** [comment]
Without logs for on_search, we can't verify. Pls check the last response sent to plotch buyer app before these flows were executed.
@sathiamour

**Comment by Girisuta** [comment]
@BLR-0118  - We are unable to trace the on_search for Mar 31. We still have issues with search on plotch , tracking bug : https://ondc-issue-logging-cohort1.atlassian.net/browse/PREPROD-257

We will try to resubmit all flows with reference buyer app again . Flow 5 has seacrh as well, kindly confirm if Flow 5 is fine so that we will resubmit till flow 4

**Comment by sathiamour** [comment]
@BLR-0118 
For Flow -2 : Non-serviceable usecase, here is the link. - https://github.com/ONDC-Official/v1.1.0-logs/blob/main/Nstore/Retail-ReferenceBuyerAPP/Flow2/on_select.json

**Comment by BLR-0118** [comment]
Yes, non-serviceable flow looks ok. Also, for serviceability, you need to send both the old & new constructs until the old one is removed

**Comment by sathiamour** [comment]
@BLR-0118 We have resubmitted the Flow-1 with the changes.
Pull Request - https://github.com/ONDC-Official/v1.1.0-logs/pull/187

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search should have both old & new serviceability construct;
2. /on_select response takes almost 7 secs (diff in Context.timestamp between /select & /on_select)?
3. /on_status: invoice should be added when order is picked up;
4. /on_update.1: 
- order_qty is invalid key;
- quote should have line item for liquidated item 238 with qty as 0;

**Comment by BLR-0118** [comment]
@sathiamour @Girisuta

**Comment by sathiamour** [comment]
> @sathiamour @Girisuta

@BLR-0118 We have updated the Flow - 1 with the changes.
Pull Request - https://github.com/ONDC-Official/v1.1.0-logs/pull/190

**Comment by BLR-0118** [comment]
@sathiamour

**Comment by sathiamour** [comment]
@BLR-0118 We have updated the Flow-1 as mentioned changes. Could you please review it.
 Pull Request - https://github.com/ONDC-Official/v1.1.0-logs/pull/197

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0

**Comment by BLR-0118** [comment]
@sathiamour
