### ISSUE TITLE
Shiprocket - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#32]
1. /on_confirm - order.created_at can't be changed as it was created in /confirm;
2. /on_update - shipping label pdf should be sent in fulfillment.start.instructions.images;
3. /on_status (pickup) - fulfillment.start.time.timestamp is mandatory;
4. /on_status (delivered) - fulfillment.end.time.timestamp is mandatory;
5. /on_cancel - fulfillment.id should be same as in /on_confirm but fulfillment state code should be set to cancelled;

**Comment by BLR-0118** [comment]
@PankajDubey

**Comment by pankajd16** [comment]
@BLR-0118 Will check and update you.

**Comment by BLR-0118** [comment]
Logs with Sellerapp
=============
1. /on_init:
- provider id "60" & item id "60" selected in /init (for which quote was 2 in /on_search) but here the quote shows as 121.8 (which is the corresponding RTO quote);

**Comment by BLR-0118** [comment]
@pankajd16

**Comment by pankajd16** [comment]
@BLR-0118

**Comment by BLR-0118** [comment]
Ok. Logistics buyer app should have called /search again but that's not happening in this case. Anyway, these logs are cleared for v1.1.0
