### ISSUE TITLE
Mytra (TSP) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#343]
- /on_action APIs should respond within 5 sec upon receving the /action APIs
- All the issues identified by the utility should be addressed and rectified.

**/on_search**

- Invalid /on_search response; should have same city code, txn id and message_id as in /search
- /message/catalog/bpp/providers/0/items/ must have required statutory requirements as mapped in the [enhanced subcategory list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0)
- /message/catalog/bpp/providers/0/items veg/non-veg categorization is mandatory for F&B categories or packaged foods in /tags
- bpp/descriptor/images can't be empty
- locations/locality is missing in /bpp/providers/
- inaccurate geocoding of gps and address in /bpp/providers/locations (gps/area_code mismatch)
- self-pickup is not supported in v1.1.0, must use other relevant fulfillment_id in /items

**/on_select**

- /fulfillments/end is not required
- /items/location_id is not required
- @ondc/org/TAT should be realistic (not 2083 days)
- "@ondc/org/item_quantity" should be integer in /quote/breakup

**/on_confirm**

- estimated pickup and delivery time ranges should be realistic and match the fulfillment category (Next day delivery)

**/on_status_delivered**

- how can delivery timestamp (/fulfillments/end/time/timestamp) be before /on_status picked call?

**/on_update**

- Invoice is not required in /documents

**/on_update (Return_Approved)**

- estimated return pickup/delivery time ranges should be realistic
- start of the time ranges can't be earlier than context/timestamp

**/on_update (Return_Delivered)**

- how can Reverse QC delivery timestamp (/fulfillments/end/time/timestamp) be before /on_update return picked call?

## Flow 2

**/on_select**

- delivery charges line item should not be included in /quote/breakup when location is not serviceable

## Flow 5

**/on_select**

- item's unit price can't be 0 when item is out-of-stock

@harshpwctech

**Comment by harshpwctech** [comment]
@bluecypher  - All the above issues have been resolved via [PR](https://github.com/ONDC-Official/v1.1.0-logs/pull/346)

Kindly review.

**Comment by bluecypher** [comment]
**/on_search**

- context/timestamp difference between /on_search and /search should be smaller than 5 sec
- old serviceability should also be provided in /locations/circle (till not deprecated)

**/on_confirm**

- pickup time range (/fulfillments/start) can't be equal to delivery time range (should match with shipping time)

**/on_status, /on_update**

- items/quantity/count should be an integer (not a decimal value)

@harshpwctech

**Comment by bluecypher** [comment]
- /on_action APIs must respond within 5 sec of the /action APIs

**/on_search**

- search by item should be supported
- veg_nonveg categorization is not required for packaged commodities

## Flow 5

**/on_search**

- catalog mandatory requirements must be present as identified by the utility's report.


@harshpwctech

**Comment by bluecypher** [comment]
@sdeIntern-PWCTech, Please rectify all the issues as identified earlier.

**Comment by bluecypher** [comment]
@BLR-0118, the Mytra (TSP) v1.1.0 logs seem fine. Please proceed with your review.

@sdeIntern-PWCTech
