### ISSUE TITLE
Channelier (LSP BAP) - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.1.0-logs#351]
## Flow 1

**/init**

- fulfillment/id should be one of the fulfillment id returned in /on_search
- payment object is not required in init

**/update**

- start instructions are mandatory in case 'ready_to_ship' = yes

## Flow 2

- similar issues as above
- unsolicited cancelation should be done from LSP with appropriate reason code (/cancel is not required)

**/cancel**

- Message Id cannot be same as /confirm Api

@ravinderTechpvec18

**Comment by abhinavv245** [comment]
## Flow 1

**/search**

- context/city code should match the city for fulfillment start location
- gps coordinates precision should be upto 6 decimal places

**/init**

- door and ward are invalid attributes in start/location/address

**/confirm**

- mandatory attribute '@ondc/org/order_ready_to_ship' is missing
- order/created_at and order/updated_at should match context/timestamp
- start/instructions/image should be in url format
- Is Auto RTS supported in /confirm?

**/update**

- location, contact, person in fulfillments/start and fulfillments/end are not required in /update

**/on_status**

- 'OrderPickedUp' is an invalid enum for fulfillment state (BAP should send NACK)

## Flow 2

- similar issues as above


#### Is RTO flow handled at logistics buyer app side

@ravinderTechpvec18

**Comment by abhinavv245** [comment]
## Flow 1

- why is the shipment marked "P2P" for inter city order (in flow 2, with the same start and end location, it is marked "P2H2P")

**/confirm**

- store gps coordinates cannot change in /confirm

## Flow 2

**/init**

- City code mismatch in /search and /init onwards
- Transaction Id should be same from /search onwards

**/confirm**

- Billing object mismatches in /init and /confirm (created_at,updated_at are different)

### Is RTO flow handled at logistics buyer app side ?

@ravinderTechpvec18

**Comment by abhinavv245** [comment]
## Flow 1

**/update**

- fulfillment/state is not required in /update
- fulfillment/state/descriptor/images is invalid

**/on_update**

- Shipping label is mandatory for P2H2P shipments in /fulfillments/start/images 

@ravinderTechpvec18

**Comment by bluecypher** [comment]
Test with one of the LSPs whose logs are verified

**/search**

- dangerous goods attribute should only be provided when payload includes hazardous goods

**/confirm**

- For P2H2P, PCC is the shipping label, no need to provide separate confirmation code
- Why is the measurement of item changed? This might change the delivery prices


@ravinderTechpvec18

**Comment by bluecypher** [comment]
@ravinderTechpvec18, all the previously identified issues should be resolved

**Comment by bluecypher** [comment]
**/update**
- context/timestamp can't be the same as /confirm timestamp
- For P2H2P, PCC is the shipping label, no need to provide separate confirmation code

@ravinderTechpvec18
