### ISSUE TITLE
Dunzo (Seller App) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#378]
**/on_search**

- store timings can be provided as fixed timing, ranging from "0600" to "2300"
- tsp_item_attributes is an invalid attribute
- @ondc/org/contact_details_consumer_care should be in the format "name,email,contact no" (name is missing in the logs)
- invalid area_code "4978438" in /locations/address/area_code

**/select**

- item unavailable in stock (as per items/quantity in catalog) can't be selected

**/on_init**

- /billing/door is invalid attribute (not present in /init)
- settlement_details can't be empty strings
- prices listed in the quote/breakup do not align with the catalog prices (are the prices changing dynamically?)

**/on_confirm**

- fulfillments/start/address is optional attribute. Anyway, why is area_code of the store changing here?
- payment/params/transaction_status is invalid key

**/on_status**

- gps of store location (/fulfillments/start/location/gps) can't change in on_status
- invoice must be present in "Order-picked-up" state and thereafter
- why are estimated pickup and drop time ranges changing in every unsolicited calls?

**/on_update**

- provider/id can't be empty

## Flow 2

**/on_select**

- item prices must be present in quote/breakup
- delivery charges line item should not be present when location is "Non-serviceable"
- other charges (tax, packing) that are 0 should not be present

## Flow 5

**/on_select**

- out-of-stock item must be present in quote/breakup with count=0

@anandyukta

**Comment by bluecypher** [comment]
**/on_search**

- @ondc/org/contact_details_consumer_care should be in the format "name,email,contact no" (name is missing in the logs)
- invalid veg/non_veg categorization; can't be set as "no" for both

## Flow 2

**/on_select (non-serviceable)**

- schema for quote/breakup should not change (quote/breakup/item is missing for title_type": "item")

## Flow 5

**/on_select**

- unit price can't be 0 for out-of-stock item in quote/breakup


@anandyukta

**Comment by bluecypher** [comment]
@anandyukta, please resolve the timestamps related issues as identified by the utility.

**Comment by anandyukta** [comment]
@bluecypher here is the PR after resolving issues identified by utility
https://github.com/ONDC-Official/v1.1.0-logs/pull/410

**Comment by bluecypher** [comment]
## Flow 3

**/on_update (Rejected)**

- Timestamp for /on_update (initiated) cannot be equal to /on_update (Return_Rejected)

## Flow 4

**/on_update (Initiated)**

- Timestamp of /on_update (Return_Initiated) can't be earlier than /update and on_status (Order-picked-up)

**/on_update (Liquidated)**

- Timestamp for /update cannot be equal to /on_update (Liquidated)


@anandyukta

**Comment by anandyukta** [comment]
@bluecypher Here you can find the fixes for the same
https://github.com/ONDC-Official/v1.1.0-logs/pull/414

**Comment by bluecypher** [comment]
@anandyukta, please resubmit flow 4 for a new txn

**Comment by anandyukta** [comment]
@bluecypher here is flow logs with new txn https://github.com/ONDC-Official/v1.1.0-logs/pull/420

**Comment by bluecypher** [comment]
@BLR-0118, the Dunzo seller app logs (v1.1.0) seem fine. Please proceed with your review.

@anandyukta
