### ISSUE TITLE
Paytm - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#40]
1. /init - billing.created_at & updated_at should match Context.timestamp for /init;
2. /confirm:
- order.created_at & updated_at should match Context.timestamp for /confirm;
- buyer_app_finder_fee_type should be "percent" (lowercase);
- following keys are invalid in payment.params: mode, vpa;

**Comment by BLR-0118** [comment]
@chiragkhannapaytm

**Comment by chiragkhannapaytm** [comment]
@BLR-0118 Do we need to update the logs in this repo as well post these fixes?

**Comment by BLR-0118** [comment]
@chiragkhannapaytm - yes

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0
