### ISSUE TITLE
Shipsy - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.1.0-logs#441]
## Flow 1

**/on_search**

- item TAT is given for 2 days, why is /items/time/timestamp provided for the date after 3 days w.r.t context/timestamp
- the approx distance between start and end location is 16km and the shipment is P2H2P, is this intentional? (otherwise realistic pincodes should be provided)
- dimensions are required in /search for P2H2P shipments (LSP should send NACK)

**/on_update**

- pickup and delivery time range should not be same

**/on_track**

- /track is applicable for hyperlocal "Immediate delivery" orders for now. (LSP should send NACK in this case)

## Flow 2

**/on_status**

- All states of RTO should be provided

@aditya-sharma2-shipsy

**Comment by abhinavv245** [comment]
## Flow 2

**/on_status**

- Provide /on_status responses for all fulfillment states prior to order cancellation

**Comment by aditya-sharma2-shipsy** [comment]
@abhinavv245 I have added the Pickup Completion log on_status call in the below PR 
https://github.com/ONDC-Official/v1.1.0-logs/pull/454

**Comment by bluecypher** [comment]
**/on_track**

- invalid NACK error response for /track; 60012 error code should be used


@aditya-sharma2-shipsy

**Comment by bluecypher** [comment]
@BLR-0118, the Shipsy LSP logs v1.1.0 seem fine. Please proceed with your review.

@aditya-sharma2-shipsy
