### ISSUE TITLE
Kiko - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#508]
- search by item should be supported
- address all the issues as identified by the log validation utility
- share unprocessed logs from the buyer app side

## Common Issues (to be resolved across all the flows)

**/on_search**

- Why orders are getting processed from disabled provider
- mapping of category_id and statutory reqs should be correct as mentioned in the enhanced subcategory list
- "@ondc/org/mandatory_reqs_veggies_fruits" is only required for Fruits and Vegetables category
- veg/non-veg categorization in /tags is not required for non F&B products
- "Fast Food" is not a valid category_id as defined in [enhanced sub-category list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0)
- Why is it taking 24 hours to ship for hyperlocal serviceability?

**/on_select**

- Why are hyperlocal orders taking 2 days to be delivered?
- invalid fulfillment category and TAT mapping in /fulfillments
- items in grocery categories are tax inclusive; tax breakup should not be provided in quote/breakup for this category
- available and maximum count of items are higher than the quantity provided in catalog; Is inventory availability changing dynamically?

**/on_init**

- /billing/address must have required property 'building'; Seller app should respond with a NACK
- item/quantity is not required in /quote/breakup in /on_init

**/on_status (Pending)**

- Order state should be "In-progress" when fulfillment is "Packed"
- documents for Invoice should be present when fulfillment state is "Order-picked-up" and thereafter
- /fulfillments/0/start/time pickup time should not be present until order is picked

**/on_status (Order-picked-up)**

- pickup timestamp should match context/timestamp and can't be future dated
- order/updated_at timestamp can't be less than the pickup time

**/on_status (Order-Delivered)**

- context/timestamp of /on_status (Order-picked-up) cannot be greater than /on_status (Order-delivered)
- delivery timestamp should match context/timestamp and can't be future dated
- order/updated_at timestamp can't be less than the delivery time

**/on_update**

- Fix all the issues as identified by the Log validation utility

## Flow 2

- /select payload is missing for /on_select (Non-serviceable)
- cancellation should be seller initiated as per Flow 2

## Flow 3

- rectify issues identify by the utility

## Flow 4,5

- invalid quote/breakup in /on_select (Out-of-stock); items should be present in quote; unit price of items must be non-zero
- /select payload is missing for /on_select (Out-of-stock)

@vickyKiko

**Comment by bluecypher** [comment]
- All the previously identified issues should be resolved
- estimated and actual timestamps of pickup/delivery/return are not captured correctly

@vickyKiko

**Comment by vickyKiko** [comment]
https://github.com/ONDC-Official/v1.1.0-logs/tree/main/Kiko-Live-Retails-Logs/Retail%20Logs

we have resolved all the above points and implemented and resubmitted the log in a new folder i.e. Retail Logs.
I've included the above URL for the same.
I have restructured the files. request you to review it. 

https://github.com/ONDC-Official/v1.1.0-logs/pull/565

**Comment by bluecypher** [comment]
## Common Issues

**/on_search**

- fssai license no. is not required for non-F&B providers

**/select**

- delivery and store location should not be same; JSON payloads must be provided with realistic use case

**/on_select**

- invalid fulfillment category and TAT mapping in /fulfillments; use “Same Day Delivery” / “Next Day Delivery” / “Standard Delivery” instead
- fulfillment_id is same in every flow; what happens in case of multiple fulfillments in an order?

**/on_status**

- order state can't change from “Accepted” in /on_confirm to “Created” in /on_status (Pending)
- estimated pickup and delivery timestamp can't be the same and should be realistic
- pickup and delivery GPS can't change

**/on_update**

- How can actual pickup and delivery timestamp be provided in Reverse QC fulfillment in /on_update (Return_Approved)
- Return_Picked: Returned item must be present in quote/breakup with count=0
- Return_Delivered: settlement_timestamp in @ondc/org/settlement_details/1/ is not captured correctly

## Flow 2

- cancellation should be initiated by seller as per Flow 2

**/on_select (Non-serviceable)**

- Incorrect context/timestamp; can't be before /select call

## Flow 4

**/on_select (OOS)**

- “@ondc/org/item_quantity” must be equal to the available count in stock
- unit price is not captured correctly in /quote/breakup/1/item/price

**/select**

- As per flow 4, available quantity must be selected after receiving /on_select (OOS)

## Flow 5

- Invalid flow; complete out-of-stock scenario is missing


@vickyKiko

**Comment by bluecypher** [comment]
**/on_confirm**

- drop off instructions can't be provided by seller app; pickup instructions need not be sent to the buyer app

**/on_status**

- order state must be In-progress when fulfillment state is "Packed"

**/on_update**

- reverse qc fulfillment state can't be Order-picked-up in Return approved state

@vickyKiko

**Comment by vijendrakiko** [comment]
@bluecypher Can you please review the RSP Logs in the same PR.

**Comment by bluecypher** [comment]
@vickyKiko, @vijendrakiko, pls re-submit logs for flow 1

**Comment by vijendrakiko** [comment]
@bluecypher Okay sure we will submit logs only for flow -1

Thanks.

**Comment by vijendrakiko** [comment]
@bluecypher Please check this PR we have updated the logs for flow-1 in this PR

https://github.com/ONDC-Official/v1.1.0-logs/pull/646

**Comment by vijendrakiko** [comment]
@bluecypher Thanks for your input and we appreciate it.
