### ISSUE TITLE
Plotch buyer app - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#51]
1. /init, /confirm - building & locality are mandatory (in billing & fulfillment address) and can't be "-";

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
@BLR-0118 Our new address UI with separate fields for the locality, landmark, etc will be rolled out during the end of April. With that release, actual values will come in building and locality instead of "-"

**Comment by BLR-0118** [comment]
@vikramacharya - locality & building are mandatory and without this, on-network logistics integration will break. You need to come up with an interim solution (such as reverse geo-code mapping from gps coords to address) until then. Without this, can't clear your logs for 1.1.0.

**Comment by vikramacharya** [comment]
Will get this released by Tuesday.

**Comment by vikramacharya** [comment]
@BLR-0118 Added provision to add building, locality in buyer apps. Logs here https://github.com/ONDC-Official/v1.1.0-logs/pull/62/files

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0
