### ISSUE TITLE
TMBill (BPP) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#515]
## Common Issues across all the flows

**/on_search**

- category_id in /message/catalog/bpp~1providers/0/items/ should be one of the valid categories as defined in [enhanced sub-category list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0)
- categories in /message/catalog/bpp~1providers/0 is not required; not a part of v1.1.0

**/on_select**

- available/maximum count of items can't increase in /on_select during live search
- is tax applicable on only one of the items?
- /fulfillments/@ondc/org/provider_name should consist of a valid delivery provider name
- deliveryCharge in /fulfillments/ is not a valid attribute
- items/quantity is not required

**/on_init**

- item/quantity is not required in quote/breakup

**/on_confirm**

- invoice should only be provided once the order is picked
- estimated pickup and delivery time ranges can't be the same
- store address is not required in /fulfillment/start/location

**/on_update**

- items are mostly liquidated in F&B categories; reverse QC can be avoided to prevent logistics charges

**/on_update (Return_Approved)**

- start and end address can't be same in ReverseQC fulfillment
- context/timestamp can't be the same as in /update call

**/on_update (Return Picked)**

- returned item should be present in quote/breakup with count=0 and total price=0
- invalid increment of tax in quote/breakup
- actual return delivery timestamp can't be provided when Return is just picked
- return pickup timestamp is not accurately captured

**/on_update (Return Delivered)**

- return delivery timestamp should be accurately captured
- refund related settlement details should be captured correctly once the second /update is received

## Flow 2

**/on_select (Non-serviceable)**

- 30011 is not a valid Location serviceability related error
- delivery charges should not be provided in quote/breakup when location is not serviceable

**/on_cancel**

- order/provider is not required

## Flow 3

**/on_update (Return Rejected)**

- update callback response should not take long; use interim state "Return_Initiated" for this

## Flow 4, 5

- suitable domain error should be provided when required quantity is not available

@sid-tmbill

**Comment by sid-tmbill** [comment]
@Rahil Shaikh ***@***.***> @TMBill Integration
***@***.***> @Haridas Shinde ***@***.***>

**Comment by bluecypher** [comment]
## Common Issues across all the flows:

**/on_search**

- /message/catalog/bpp/providers/items/category_id should be one of the valid categories as defined in [enhanced sub-category list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0)
- descriptor values must be present for every item in bpp/providers/items

**/on_select**

- inventory (available/maximum count) should be updated when items are selected
- provider_location is not a valid attribute

**/on_status (Order-picked-up)**

- pickup timestamp (/fulfillments/start/time/timestamp) can't be earlier than /on_status (Accepted) call

**/on_update (Approved)**

- How can actual return pickup timestamp be provided in /on_update (Approved)
- estimated time ranges should be correctly managed; can't be before context/timestamp

## Flow 4

- As per flow 4 only certain quantity of an item should be unavailable instead of complete out-of-stock
- item can't be out-of-stock when available in the inventory


@sid-tmbill

**Comment by sid-tmbill** [comment]
PR is submitted which will fix this issue #555

**Comment by bluecypher** [comment]
**/on_select**

- quantity object is not reqruired in /items

**/on_confirm**

- estimated time range should not precede the context/timestamp

**/on_status**
- invoice is not generated correctly. The invoice must have the same order amount as present in the APIs

**/on_cancel**

- order/provider is not required

## Flow 4

**/on_select (OOS)**

- incorrect management of inventory; @ondc/org/item_quantity count is 2 whereas inventory shows out of stock

## Flow 5

**/on_select (OOS)**

- complete out-of-stock items should not be present in the inventory


**Ques:** Are unsolicited calls for all the fulfillment states supported?


@sid-tmbill

**Comment by sid-tmbill** [comment]
Ques: Are unsolicited calls for all the fulfillment states supported?
Ans: Yes

**Comment by sid-tmbill** [comment]
PR is submitted which will fix this #564

**Comment by bluecypher** [comment]
@sid-tmbill
