### ISSUE TITLE
Shikhar (HUL) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#518]
### Common Issues across all the Flows

**/on_search**

- inaccurate mapping of store location (gps and address)
- category_id and statutory reqs should be mapped correctly as per the (enhanced subcategory list)[https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0]
- "@ondc/org/mandatory_reqs_veggies_fruits" is only required for "Fruits and Vegetables" category
- fssai license no is only required for F&B categories
- pincode serviceability is not supported by most of the buyer apps

**/on_select**

- invalid mapping of fulfillment category and TAT; Immediate Delivery should only be used where TAT <= 60 mins

**/on_status**

- all the interim states should be provided for verification
- Invoice can't be empty when fulfillment state is "Order-picked-up" and thereafter
- estimated pickup and delivery time ranges should be realistic and feasible
- order pickup timestamp (/fulfillments/start/time/timestamp) is not captured correctly

**/on_update (Initiated)**

- context/timestamp can't be the same as /update timestamp

**/on_update (Approved)**

- exact return pickup and delivery timestamp can't be provided
- estimated return pickup and delivery timestamp

**/on_update (Picked)**

- unit price of returned item should be present in quote/breakup

**/on_update (Delivered)**

- missing /on_update call for "Return_Delivered" state

## Flow 2

**/on_select (Non-serviceable)**

- delivery charges should not be present when location is not serviceable

**/on_cancel**

- Cancellation reason ID is not valid for order cancellation before shipping

## Flow 3

**on_update (Rejected)**

- update callback should not take long; use interim state Return_Initiated for this

### Provide unprocessed logs from the buyer app side

@ucansubodh1

**Comment by bluecypher** [comment]
@ucansubodh1, all the previously identified issues should be resolved.

**Comment by bluecypher** [comment]
**/on_search**

- "net_quantity_or_measure_of_commodity_in_pkg" must have a valid quantity value along with UOM
- provider/id is same as fulfillment/id. What happens in case of multiple fulfillments?

**/on_confirm**

- estimated pickup and delivery time ranges are not in accordance with the time_to_ship and TAT provided earlier. Why?

**/on_status (Packed)**

- Invoice should only be provided once the order is picked

**/on_status (Picked)**

- pickup timestamp (/fulfillments/start/time/timestamp) can't be earlier than pending/packed timestamp

**/on_update (Approved)**

- invalid start and end location in Reverse QC fulfillment (should be swapped for reverse shipment)

**/on_update (Picked)**

- returned item must be present in the quote/breakup with the remaining quantity count

#### FYI call for refund must be handled and details must be appended as part of settlement trail

## Flow 3

- update callback should not take long; use interim state Return_Initiated for this


@ucansubodh1

**Comment by bluecypher** [comment]
**/on_select**

- Same Day Delivery can't have a TAT of 1 Day; should be delivered within the same date
- quantity of inventory (available/maximum count of items) should be updated once items are selected

**/on_confirm**

- same day delivery should be fulfilled within the same date as context/timestamp (delivery time range can't be of next day)

#### FYI call for refund must be handled and details must be appended as part of settlement trail


@ucansubodh1

**Comment by Sushrut-269** [comment]
@bluecypher We have agreed to have TAT of 1 day for the Same delivery orders since the logs are generated in the night hence the time stamp of next day is getting stamped there, this should not be issue, please help in getting this signed off. Thanks

**Comment by bluecypher** [comment]
**/on_select**

- provider is disabled in the catalog; How can order be processed? 

#### Why is refund information not appended to the settlement details in /on_update after receiving the second /update call?

**Comment by bluecypher** [comment]
@Sushrut-269 @ucansubodh1

**Comment by ucansubodh1** [comment]
@bluecypher As per the below QA test cases, if store is offline , we are sending label as "disable".. If consumer proceed with this sore, we are retuning domain error with code "30009"

bpp/providers.time.label should be either enable or disable.

We will be checking this test case by asking seller apps to disable any one the provider. In this case, a Provider.label value should be disabled.

**Comment by bluecypher** [comment]
@BLR-0118, the Shikhar Seller App logs (v1.1.0) seem fine. Pls proceed with your review.

@ucansubodh1

**Comment by Sushrut-269** [comment]
@bluecypher @BLR-0118 Thanks for approving the logs.
