### ISSUE TITLE
Gofrugal retail seller app - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#52]
Flow 1
====
1. /on_status_packed:
- the quote object has changed from what was sent in /on_confirm with the addition of breakup line items for tax. Why? Also, when taxes are added, it is at the item level and the item_id has to be assigned;
2. /on_status_pickedup:
- order has been picked up means - fulfillment.start.time.timestamp is mandatory (done correctly). However, fulfillment.end.time.timestamp can only be assigned after order is delivered (assigning here is incorrect);
3. /on_status_outfordelivery:
- above timestamps in 2 changed again. Why? Once, order is picked up & pickup time assigned (start.time.timestamp), it shouldn't change;
4. /on_status_delivered:
- same issue as 3 above;
5. /on_update:
- why's a new fulfillment id assigned here? (same issue in flow 3 as well)
- return states are capital case ("Liquidated", not "LIQUIDATED; "Return_Rejected", not "RETURN_REJECTED");

**Comment by BLR-0118** [comment]
@SherinShafa27

**Comment by SherinShafa27** [comment]
@BLR-0118 fixed the above. kindly check it.

**Comment by SherinShafa27** [comment]
is logs reviewed?? @BLR-0118

**Comment by BLR-0118** [comment]
Flow 1
====
1. This log is for /select but Context.action shows "on-select". Also, area_code is "undefined". How did you get this?

**Comment by SherinShafa27** [comment]
@BLR-0118 When i took logs for resubmission from pre-prod buyer app,got select like that. now its coming correctly. u can check in other flows. kindly update the review status.

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0
