### ISSUE TITLE
Zeitgeist Retail (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#537]
- /context/domain must be "ONDC:NTS10"

**/receiver_recon**

- settlement_reference in "@ondc/org/settlement_details" should be the same as "settlement_reference_no" in /orders

**/on_receiver_recon**

- /message/orderbook/orders/0/order_recon_status must be "02"
- orderbook/orders/transaction_id must be the same as in /receiver_recon
- /message/orderbook/orders/0/counterparty_diff_amount/value must be string and upto 2 decimal places

@akashsonwalkar

**Comment by RupalSingla** [comment]
correction Flow:

/receiver recon:

- Needs to send 5 order flows .

/on_receiver_recon:

- Why is "recon_status": "01" included in the on_receiver recon? This information may not be necessary.
- The "counterparty_diff_amount" should not have in negative value 

@akashsonwalkar

**Comment by RupalSingla** [comment]
/on_receiver_recon:

order_recon_status can't be "03"; should be "02"
- timestamp can't be earlier than /receiver_recon timestamp

@akashsonwalkar

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@akashsonwalkar
