### ISSUE TITLE
Kiko (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#538]
**/receiver_recon**

- /message/orderbook/orders/0/payment/@ondc/org/settlement_details/1/settlement_status must be equal to constant (PAID)
- settlement_counterparty should be "seller-app"

**/on_receiver_recon**

- context/timestamp can't be the same as /receiver_recon
- invalid ttl property in /context
- /message/orderbook/orders/0 must have required property 'counterparty_diff_amount'
- /message/orderbook/orders/0 must have required property 'message'
- invalid value of settlement_reference_no
- invalid value of counterparty_recon_status for successful txn
- settlement_id mismatches
- txn id mismatches

@vickyKiko, please perform QA before resubmitting the logs.

**Comment by RupalSingla** [comment]
## Flow 1
/on_receiver_recon
 message.orderbook.orders.transaction_id must be similar to message.orderbook.orders.transaction_id

@vickyKiko

**Comment by vijendrakiko** [comment]
@RupalSingla Can you please check again the RSP logs in our current PR.

**Comment by vijendrakiko** [comment]
@RupalSingla Any update on rsp log review please check.

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@vickyKiko @vijendrakiko
