### ISSUE TITLE
TMBill (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#539]
- context/domain must be ONDC:NTS10

**/receiver_recon**

- settlement_refernce in /orders/@ondc/org/settlement_details mismatches with settlement_reference_no in /orders

**/on_receiver_recon**

- /message/orderbook/orders/0/counterparty_diff_amount/value must be string
- /message/orderbook/orders/message (optional property) must be an object

## Flow 2

**/on_receiver_recon**

- /message/orderbook/orders/0/order_recon_status must be equal to constant (02)

@sid-tmbill

**Comment by sid-tmbill** [comment]
PR is Submitted which will fix this issue #543

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@sid-tmbill
