### ISSUE TITLE
Medpay (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#540]
**/receiver_recon**

- order/updated_at timestamp can't be earlier than settlement_timestamp
- deduction_by_collector can't be 0 when buyer app finder fee is non-zero

**/on_receiver_recon**

- /message/orderbook/orders/0/order_recon_status must be "02" (Final)

## Flow 2

- Invalid flow; should be as per the test case scenario

@medpay-vishal-kumar

**Comment by bluecypher** [comment]
**/receiver_recon**

- /message/orderbook/orders/1/payment/@ondc/org/settlement_details/0/settlement_timestamp must be in valid date-time format
- payment/params/transaction_id can't be the same as orders/transaction_id; orders/transaction_id should remain the same in an orderbook
- Why is time difference between context/timestamp and updated_at timestamp large?


@medpay-vishal-kumar

**Comment by medpay-vishal-kumar** [comment]
Hey @bluecypher, thanks for the review and feedback. Just have one confusion: 
- "settlement_timestamp": "2023-09-03T10:42:26.598Z"
Above line is the settlement_timestamp. It is a valid date time stamp used everywhere. Please correct me if i am wrong or misunderstood the point.

**Comment by medpay-vishal-kumar** [comment]
Have fixed the issues related to RSP, please find the PR here:
https://github.com/ONDC-Official/v1.1.0-logs/pull/570

Kindly merge and review. Thank you!

**Comment by medpay-vishal-kumar** [comment]
Hey @bluecypher,

Have fixed the transaction_id issue across orderbook. Please find the PR here: https://github.com/ONDC-Official/v1.1.0-logs/pull/577

Kindly merge and review the logs.

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@medpay-vishal-kumar

**Comment by medpay-vishal-kumar** [comment]
Thank you @bluecypher .
