### ISSUE TITLE
Oogashop (logistics buyer) - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.1.0-logs#560]
## Flow 1 

- Message Id cannot be same for different sets of APIs

**/search**

- provider/time/schedule/times should be removed

**/init**

- billing/created_at and updated_at does not match context timestamp - "2023-09-05T07:30:20.506Z", also timestamps not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format
- why is buyer app sending settlement details if BAP is collecting the payment

**/on_init**

- item_id and title_type are invalid attributes in quote/breakup (buyer app should send NACK)
- payment must have required property 'type' (schema error)

**/confirm**

- billing/created_at and updated_at mismatches in /billing in /init and /confirm, also timestamps not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format
- @ondc/org/linked_order/items/quantity/measure/value must be number

**/update**

- updated_at does not match context timestamp - \"2023-09-05T07:31:17.770Z\"

**/on_status**

- /fulfillments must have required property 'type'
- context must have required property 'bpp_id' and 'bpp_uri'
- item_id and title_type are invalid attributes in quote/breakup 
- payment must have required property 'type' 
- fulfillments/start/time must have required property 'range' for fulfillment state -Order-delivered
- fulfillments/end/time must have required property 'range' for fulfillment state -Order-delivered
- 'awb_number' is an invalid attribute in /fulfillments
- buyer app should send NACK for all such schema errors

## Flow 2

- similar issues as Flow 1
- Incorrect Flow as per context/timestamps - (on_search,search,init,on_init,confirm,on_confirm,update,on_update,on_status,on_cancel)

**/on_status_picked**

- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

**/on_cancel**

- fulfillment_type is an invalid attribute in /fulfillments 

@oogashop

**Comment by abhinavv245** [comment]
## Flow 1 and 2

- Message Id cannot be same for different sets of APIs (/confirm and /update)

**/confirm**

- billing/created_at and updated_at mismatches in /billing in /init and /confirm (billing object should not change)
- linked order total price in /confirm does not match the price in @ondc/org/payload_details in /search

**/update**

- what is the purpose of the /update call as order is marked ready_to_ship = yes in /confirm

@oogashop

**Comment by oogashop** [comment]
Hi @abhinavv245 we have submitted our logs again at PR https://github.com/ONDC-Official/v1.1.0-logs/pull/580 . Please review them.

**Comment by oogashop** [comment]
Hi @abhinavv245 our IGM logs are merged too, please review them if possible.

**Comment by oogashop** [comment]
Hi @abhinavv245 we have submitted our logs again at PR https://github.com/ONDC-Official/v1.1.0-logs/pull/580 . Please merge and review.
Thanks and Regards

**Comment by abhinavv245** [comment]
## Flow 1 and 2

- Message Id cannot be same for different sets of APIs

**/search**

- fulfillment/end/location/gps cannot be equal to start/location/gps '\"12.910816, 77.546946\" (how is buyer app handling this)
- context/timestamp difference between on_search and search should be smaller than 1 sec (LSP with lower callback response time should be procured for optimized cascaded flow)

**/init**

- invalid value of tax_number provided in /billing
- start and end location and contact details should not be same

**/confirm**

- values of PCC and DCC should be appropriate in fulfillments/start and end instructions 
- weight of individual item is not in sync with the entire order weight in /@ondc/org/linked_order
- additional_desc is not required in start and end/instructions in fulfillments (in /update as well)
- payment/@ondc/org/collection_amount is required for payment/type 'ON-FULFILLMENT'

### Kindly test with a verified NP in Pre-prod environment

@oogashop @tanya-ondc

**Comment by abhinavv245** [comment]
Logs rejected. Kindly test with a verified NP in Pre-prod environment.

**Comment by oogashop** [comment]
Hi @abhinavv245 , we have submitted our logs at https://github.com/ONDC-Official/v1.1.0-logs/pull/635 which have been test with a verified NP whizzard whose contact was provided by Mr. Rohit from ONDC team. Please review these logs.

**Comment by abhinavv245** [comment]
## Flow 1

- Message Id cannot be same for different sets of APIs (init,confirm,update)

**/search**

- Reverse Geocoding for `start` failed. Area Code 560001 not matching with 12.910816, 77.546946 Lat-Long pair
- Reverse Geocoding for `end` failed. Area Code 560001 not matching with 12.910900, 77.546787 Lat-Long pair

**/init**

- /init/context must have required property 'ttl'

**/confirm**

- /confirm/message/order/billing/created_at mismatches in /billing in /init and /confirm
- /confirm/message/order/billing/updated_at mismatches in /billing in /init and /confirm
- /confirm/message/order/@ondc/org/linked_order/items/quantity/measure/value must be number
- /confirm/message/order/@ondc/org/linked_order/order/weight/value Payload weight mismatches from /search

**/update**

- /update/context must have required property 'ttl'
- /update/message/order/fulfillments/start and end need not have additional properties (location,contact,person)
- /update/message/order/@ondc/org/linked_order/items/quantity/measure/value must be number
- /update/message/order/@ondc/org/linked_order/order/weight/value Payload weight mismatches from /search
- /update/message/order/updated_at does not match context timestamp - "2023-10-14T11:55:23.407Z"

**/on_update**

- /on_update/message/order/created_at mismatches in /confirm and /on_update

**/on_status** (buyer app should send NACK in case of descrepancies from LSP end, needs to be handled)

- /on_status/message/order/state must be equal to one of the allowed values (Created,Accepted,In-progress,Completed,Cancelled)
- /on_status/message/order/quote/breakup must have required property '@ondc/org/item_id'
- /on_status/message/order/quote/breakup must have required property '@ondc/org/title_type'
- /on_status/message/order/payment must have required property 'type' (payment__type is an invalid attribute)
- Order state should be 'In-progress' for fulfillment state - Order-picked-up",
- Pickup timestamp (fulfillments/start/time/timestamp) is required for fulfillment state - Order-picked-up
- Order state should be 'In-progress' for fulfillment state - Out-for-delivery",
- Pickup timestamp (fulfillments/start/time/timestamp) is missing for fulfillment state - Out-for-delivery
- Pickup timestamp (fulfillments/start/time/timestamp) is missing for fulfillment state - Order-delivered
- Delivery timestamp (fulfillments/end/time/timestamp) is required for fulfillment state - Order-delivered

## Flow 2 (Buyer app should send NACK for all schema errors)

**/on_update**

- /on_update/0/message/order/updated_at should be greater than order/created_at "2023-10-14T12:07:00.119Z" in /confirm

**/on_status**

- /on_status/message/order must NOT have additional properties (init_message_order) (RTO Initiated and Delivered)
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format (Return Initiated)

**/on_cancel**

- /on_cancel/0/message/order must NOT have additional properties (cancel_order)

@oogashop 

P.S. @jeevansanju could you please address these issues from LSP's end

**Comment by jeevansanju** [comment]
@abhinavv245 As discussed over call by Manasa, these issues were not from our end. Kindly let us know if any other clarification is required from our end.

**Comment by oogashop** [comment]
Hi @abhinavv245 , we have submitted logs with the modifications required at https://github.com/ONDC-Official/v1.1.0-logs/pull/641 . Please review the logs.

**Comment by abhinavv245** [comment]
## Flow 1 and 2

**/init**

- /init/0/message/order/billing/tax_number should be valid

**/update**

- null values to be removed (provider is not required in /order)

**/on_update**

- /on_update/0/message/order/fulfillments/0/id mismatch from /init (how is buyer app handling)

**/on_cancel** (buyer app should send NACK for schema errors)

- /on_cancel/0/message/order/fulfillments/0 must NOT have additional properties (fulfillment_type)
- order/fulfillments/0 must have required property 'type'

@oogashop

**Comment by oogashop** [comment]
Hi @abhinavv245 , we have made the recommended changes, please review them.

**Comment by abhinavv245** [comment]
## Flow 1 and 2

**/search**

- Reverse Geocoding for `start` failed. Area Code 560001 not matching with 12.910816, 77.546946 Lat-Long pair.
- Reverse Geocoding for `end` failed. Area Code 560001 not matching with 12.910900, 77.546787 Lat-Long pair.

**/init**

- /init/0/message/order/billing/tax_number should be valid

**/confirm**

- /confirm/0/message/order/@ondc/org/linked_order/order/weight/value must be number

**/update**

- /update/0/message/order/@ondc/org/linked_order/order/weight/value must be number

@oogashop

**Comment by oogashop** [comment]
Hi @abhinavv245 we have submitted our logs again along with log reports generated by log validation utility. Please review them.

**Comment by bluecypher** [comment]
Logs cleared for Logistics Buyer v1.1.0

@oogashop
