### ISSUE TITLE
ITCStore - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#58]
Flow 1
====
1. /on_search:
- item.category_id: use one of the non-deprecated categories from this [list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0);
- contact_details_consumer_care should be in this format (as per the API contract): "name,email,contactno";
- difference in timestamp between /search & /on_search is > 10sec. Why?
2. /on_select:
- difference in response between /select & /on_select is > 4 sec. This will timeout in prod.
3. /on_confirm:
- billing.created_at & updated_at timestamp changed. It needs to be the same as what was set in /init;
- following keys need to be removed: withholding_amount, return_window, settlement_basis, settlement_window;
- order.updated_at should be updated to Context.timestamp;
4. /on_status_picked:
- message_id is same as /on_confirm. This is incorrect. Every unsolicited call should have a new message_id;
- building & locality in billing & fulfillment address has spaces inserted which is wrong. Should be the exact info from /init;
- when order is picked, the pickup time (fulfillment.start.time.timestamp) needs to be provided;
- start.contact.phone is in different format from what was provided in /on_confirm;
- order.updated_at should be updated to Context.timestamp;
5. /on_status_delivered:
- Check Context.timestamp (cut & paste from somewhere?);
- same issues as 4 above (in this case, the delivery time needs to be provided);
6. /on_update:
- quote.breakup only has unit price, not total price;

Flow 3
====
1. /on_update: return is rejected which means the order value (total & breakup for quote) should be the same as in /on_confirm;

**Comment by BLR-0118** [comment]
@ITCStore - pls make sure logs are submitted in the correct format, otherwise, won't be reviewed

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- schedule.holidays: empty array should be "[]". Is what you're showing an empty array?
2. /on_status_packed:
- item.quantity.count should be integer;
3. /on_status_out_for_delivery:
- pickup time (fulfillment.start.time.timestamp) format is invalid. Also, why did this change from what was set in 2?
4. /on_status_delivered:
- pickup time & delivery time (fulfillment.end.time.timestamp) are now same. How?
5. /on_update:
- item.quantity.count should be integer;

Flow 2
====
Payload for non-serviceable usecase?

Flow 4
====
1. /on_select:
- item.quantity.count should be integer. Why is it string here but integer in other flows?

**Comment by BLR-0118** [comment]
@ITCStore

**Comment by BLR-0118** [comment]
1. Flow 1: /on_update:
- quote should show the latest order value & breakup, with the liquidated item quantity set to 0;
2. Flow 2 : still haven't seen a non-serviceable payload. Even if you're servicing pan-India, there may be emergency cases where either the pickup or drop location may not be serviceable.

**Comment by BLR-0118** [comment]
@ITCStore

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_update:
- /confirm has following items: "QM VEGGIE 70-PK", "MAGIC MASALA 93" (1 each);
- /update is for return of: "QM VEGGIE 70-PK";
- /on_update should only have 2 entries for items: "QM VEGGIE 70-PK" (with forward shipment fulfillment_id & liquidated status), "MAGIC MASALA 93" (with forward shipment fulfillment id);
- /on_update should also have the forward shipment fulfillment object;

**Comment by ITCStore** [comment]
@BLR-0118 Returns to  be initiated after delivery. Hence, what is forward shipment fulfillment_id. Do we need need to generate fresh fulfilment id or we need to use the one we created in on_select.

Also, what will be the value for fulfillments.type and state.descriptor.code and start.time.range

**Comment by BLR-0118** [comment]
1. /on_update:
- liquidated item should have an entry in quote.breakup with item_quantity set to 0;

**Comment by BLR-0118** [comment]
@ITCStore

**Comment by ITCStore** [comment]
@BLR-0118 change has been implemented. http://jsonblob.com/1088402844876554240
