### ISSUE TITLE
Qaddoo (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#595]
Invalid JSON payloads; refer to the RSF document for the correct APIs to be integrated.

@rajeevrawat982

**Comment by bluecypher** [comment]
**/receiver_recon**

- /context/ttl must be "P2D" (instead of PT2D)
- many invalid attributes; refer API contract for all the valid attributes
- order_recon_status can't be null
- invalid value of settlement_window; must be in ISO8601 duration format
- created_at and updated_at timestamps can't be same in /orderbook/orders


@rajeevrawat982

**Comment by rajeevrawat982** [comment]
@bluecypher  fixed and raised another PR [https://github.com/ONDC-Official/v1.1.0-logs/pull/624] .

- covered all the params this time. 
- order_recon_status is marked null in both of the provided data sample json and datasheet schema that created a confusion. 
- ISO duration formats are fixed.
- timestamps are fixed now we mapped the updated_at with receciver_recon call timestamp.

**Comment by bluecypher** [comment]
- settlement_timestamp can't be same as orderbook created_at timestamp

@rajeevrawat982, resubmit logs for settlement of any one order.

**Comment by rajeevrawat982** [comment]
@bluecypher They are not same both were created in close proximity so only having difference in some milli seconds. 

"created_at": "2023-10-11T04:59:31.700Z",  ,  "settlement_timestamp": "2023-10-11T04:59:31.487Z"

**Comment by bluecypher** [comment]
@rajeevrawat982, settlement timestamp can't be earlier than orderbook creation timestamp.

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0.

@rajeevrawat982
