### ISSUE TITLE
OLA BA (IGM ) Compliance Check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.1.0-logs#661]
Flow 1

**/issue** 
- /message/issue/status must be equal to one of the allowed values (OPEN,CLOSED)
- /message/issue/issue_actions/complainant_actions/0/updated_by/contact must have required property 'phone'
- Organization's Name for /issue api in message/issue/issue_actions/complainant_actions/[0] mismatched with BAP ID

**/on_issue** 
- 'created_at' should match issue's 'created_at'

**/on_issue_status** 
- 'created_at' should match issue's 'created_at'

**/on_issue_status(unsolicited)** 
- Message  ID mismatch in /issue_status and /on_issue_status
- 'created_at' should match issue's 'created_at'

7 on_issue_closed.json (extra file present)
Message_id same in each call except for on_issue_status(unsolicited)
Flow 2
**/issue** 
- /message/issue/issue_actions/complainant_actions/0/updated_by/contact must have required property 'phone'
- Organization's Name for /issue api in message/issue/issue_actions/complainant_actions/[0] mismatched with BAP ID

**/on_issue** 
- context timestamp should be greater than or equal to updated_at in on_issue

**/on_issue_status** 
- Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[2] mismatched with BAP ID
- Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[2] mismatched with domain in context
- context timestamp should be greater than or equal to updated_at in on_issue_status

**/on_issue_status(unsolicited)** 
- Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[3] mismatched with BAP ID
- Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[3] mismatched with domain in context
- context timestamp should be greater than or equal to updated_at in on_issue_status

Message_id same in each call except for 3.on_issue_status_inProgress
Flow 3
**/issue** 
- /message/issue/issue_actions/complainant_actions/0/updated_by/contact must have required property 'phone'
- Organization's Name for /issue api in message/issue/issue_actions/complainant_actions/[0] mismatched with BAP ID

**/on_issue** 
- context timestamp should be greater than or equal to updated_at in on_issue

**/on_issue_status** 
- Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[3] mismatched with BAP ID
- Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[3] mismatched with domain in context

**/on_issue_status(unsolicited)** 
- Message  ID mismatch in /issue_status and /on_issue_status
- Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[2] mismatched with BAP ID
- Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[2] mismatched with domain in context

Message_id same in each call except for on_issue_status(unsolicited)

@Anoopsmohan

**Comment by Anoopsmohan** [comment]
@RupalSingla aforementioned issues have been fixed.  Kindly review it again.
PR: https://github.com/ONDC-Official/v1.1.0-logs/pull/673

**Comment by Anoopsmohan** [comment]
Hi @RupalSingla, Kindly review this and suggest if any more changes are required.

**Comment by RupalSingla** [comment]
format for created_at and update_at is wrong in all the flows .

@Anoopsmohan

**Comment by Anoopsmohan** [comment]
@RupalSingla  are you talking about **issue.json** in all flows? Not seeing any issue in other files. Please confirm.

**Comment by Anoopsmohan** [comment]
Hi @RupalSingla 

Date format issue has been fixed and resubmitted the logs Flow1. Same fix is applicable for all the flows. 

PR - https://github.com/ONDC-Official/v1.1.0-logs/pull/686

**Comment by Anoopsmohan** [comment]
@RupalSingla any update here?

**Comment by Rishabh-ondc** [comment]
issue_closed
- complainant_actions trail object for OPEN has changed from issue (open) payload, please check (short_desc changed, contact.email changed, contact.phone missing, person.name showing unavailable)
- complainant_actions.contact.phone missing in trail object for CLOSE
- contact.email and name changed between the OPEN and CLOSE object, please check

@Anoopsmohan

**Comment by Anoopsmohan** [comment]
@Rishabh-ondc This was due to the wrong configuration in our ticketing system. The issue has been resolved and resubmitted the **flow-1 l**ogs. Could you verify as soon as possible?
PR - https://github.com/ONDC-Official/v1.1.0-logs/pull/702

**Comment by Rishabh-ondc** [comment]
issue_closed
- contact.email and person.name has changed between "issue" and "issue_closed" logs for "OPEN" action, please check

@Anoopsmohan

**Comment by Anoopsmohan** [comment]
@Rishabh-ondc  this has been fixed. Please reverify.
PR: https://github.com/ONDC-Official/v1.1.0-logs/pull/704

**Comment by Rishabh-ondc** [comment]
Logs cleared. 

@Anoopsmohan

**Comment by Anoopsmohan** [comment]
Thanks @Rishabh-ondc
