### ISSUE TITLE
OLA LSP (RSF) - Compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.1.0-logs#666]
In "on_receiver call" and "receive_recon call,"  the "timestamp" for the "on_receiver call" should not be  greater than the "receive_recon call."

@Anoopsmohan

**Comment by Anoopsmohan** [comment]
@mherle FYI

**Comment by mherle** [comment]
@RupalSingla Issues are addressed in [PR 676](https://github.com/ONDC-Official/v1.1.0-logs/pull/676). Pls check this.

**Comment by bluecypher** [comment]
- discrepancy in the order id: 6e037b91-8e62-4513-a6a6-d5a39e87570f; both the flows show different counterparty recon status.
- order_recon_status can't be 01 in /on_receiver_recon; should be 02
- counterparty_diff_amount can't have -ve value


@mherle

**Comment by Poornima-Aithal** [comment]
@bluecypher All issues have been fixed. Please review: https://github.com/ONDC-Official/v1.1.0-logs/pull/677

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@mherle @Poornima-Aithal

**Comment by mherle** [comment]
Thank you @bluecypher and @RupalSingla . Appreciate your quick revert and patience.
