### ISSUE TITLE
OLA LSP(IGM) - Compliance Check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.1.0-logs#667]
issue_status
- /message must have required property 'issue_id'

extra files present (issue.py   & issue_closed.json) 

@mherle

**Comment by mherle** [comment]
@RupalSingla / @Rishabh-ondc  

There is [Issue 667 in v1.1.0-logs](https://github.com/ONDC-Official/v1.1.0-logs/issues/667) as well as [Issue 1246 in verification logs](https://github.com/ONDC-Official/v1.1.0-logs/issues/667). 
Which one should I update now ?

Can one of you close the other as duplicate ? I need only one active issue to record in the ORC sheet.

**Comment by mherle** [comment]
@RupalSingla / @Rishabh-ondc  

Addressed in [PR 675](https://github.com/ONDC-Official/v1.1.0-logs/pull/675). Pls check

**Comment by RupalSingla** [comment]
on_issue

-  issue.created_at has changed..

**on_issue_status_resolved - **

- context.message_id has not changed for the unsolicited call

@mherle

**Comment by Poornima-Aithal** [comment]
All issues have been fixed. @RupalSingla Please review: https://github.com/ONDC-Official/v1.1.0-logs/pull/678

**Comment by mherle** [comment]
@RupalSingla / @Rishabh-ondc 
Can this be reviewed today ?

**Comment by Rishabh-ondc** [comment]
Logs cleared.

@mherle @Poornima-Aithal

**Comment by mherle** [comment]
Thank you @Rishabh-ondc
