### ISSUE TITLE
Tata Digital BA (RSF) - Compliance Check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.1.0-logs#669]
- orderbook/orders/transaction_id should be same for all the orders in an orderbook
- In order id : 66930301 has counterparty_recon_status :03 ,  which needs to be 01

@barjinderpaul-mp

**Comment by barjinderpaul-mp** [comment]
@RupalSingla Which flow and API call are you referring to in this comment - _In order id : 66930301 has counterparty_recon_status :03 , which needs to be 01_?

In happy flow for order id - 66930301, settlement_amount is equal to params.payment.amount, thus we have sent counterparty_recon_status = 01

In correction flow for order id - 66930301, settlement_amount is less than params.payment.amount by Rs.10, thus we have sent counterparty_recon_status=03 in on_receiver_recon based on the specification of counterparty_recon_status mentioned in official ONDC docs - https://github.com/ONDC-Official/protocol-network-extension/blob/main/specifications/rsp/enums/counterparty_recon_status.json#L5

Can you please explain where is the gap?

**Comment by RupalSingla** [comment]
In order id : 66930301 is having two flows one successful and the correction flow  which can be possible for same orderIid

And pls avoid the above issue

@barjinderpaul-mp

**Comment by barjinderpaul-mp** [comment]
Are we good to go (Logs cleared for RSP) or is it required - _orderbook/orders/transaction_id should be same for all the orders in an orderbook_?

If it is required, we have created this PR for it, please review it - https://github.com/ONDC-Official/v1.1.0-logs/pull/670
@RupalSingla

**Comment by barjinderpaul-mp** [comment]
@RupalSingla can you please confirm?

**Comment by bluecypher** [comment]
- Why is the receiver_recon called with a delay of many days? (check settlement_timestamp and context/timestamp)
- Why is there a discrepancy in the counterparty_recon_status for order ID 66930301? Both flows show different statuses.


@barjinderpaul-mp

**Comment by barjinderpaul-mp** [comment]
1. We had done the settlement earlier and just initiated new receiver recon for these.
2. counterparty_recon_status is 01 in happy flow since the settlement amount and payment amount is same. It is 03 from seller due to the seller received lesser amount (Rs.10), thus seller sent counterparty_recon_status based on this document - 
https://github.com/ONDC-Official/protocol-network-extension/blob/main/specifications/rsp/enums/counterparty_recon_status.json#L5
Also, this would be seller side thing, would not be required in BA?

**Comment by barjinderpaul-mp** [comment]
As discussed with Rishabhanand, we have resubmitted the correction flow for a different order id. It's a small change, please check once - 
https://github.com/ONDC-Official/v1.1.0-logs/pull/681/
@bluecypher @bluecypher

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@barjinderpaul-mp

**Comment by barjinderpaul-mp** [comment]
Thanks @bluecypher
