### ISSUE TITLE
Oogashop (RSF) -compliance  check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.1.0-logs#689]
reciver_recon

- /context/timestamp must match format "date-time"
- /message/orderbook/orders/payment/@ondc~1org~1settlement_details/0/settlement_timestamp must match format "

@oogashop

**Comment by oogashop** [comment]
Hi @RupalSingla , we have submitted RSF logs again at https://github.com/ONDC-Official/v1.1.0-logs/pull/690 . Please review and suggest.

**Comment by RupalSingla** [comment]
- For "receiver_recon," it is necessary to have an "on_receiver_recon"
- For a single order book, a minimum of 5 orders is required.

@oogashop

**Comment by oogashop** [comment]
Hi @RupalSingla , we have made these changes at https://github.com/ONDC-Official/v1.1.0-logs/pull/714 . Please review.

**Comment by bluecypher** [comment]
Previously identified issues should be resolved.

Flow 1: 5 orders should be a part of a single orderbook  as per the test scenario

@oogashop

**Comment by bluecypher** [comment]
Logs approved for RSF v1.0.0

@oogashop
