### ISSUE TITLE
Phonepe (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/v1.1.0-logs#710]
issue
- context.core_version should be 1.0.0
- source.network_participant_id is missing
- complainant_actions.remarks in an invalid attribute, please refer to the API contract
- complainant_actions.updated_by is missing
- complainant_actions.cascaded_level is not required

issue_status
- context.core_version should be 1.0.0

Clarifications
- Provide logs for issue close call as well

@thsubaku9

**Comment by thsubaku9** [comment]
Acknowledged. Will update here once correct payloads have been used & uploaded for igm transactional flows

**Comment by thsubaku9** [comment]
New payload has been created in -> https://github.com/ONDC-Official/v1.1.0-logs/pull/728

@Rishabh-ondc

**Comment by Rishabh-ondc** [comment]
Logs cleared.

@thsubaku9
