### ISSUE TITLE
GRAB (RSF) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.1.0-logs#732]
Orderbook must have 5  orders .

FLOW 1 : 
//on_receiver_recon
counterparty_recon_status  is having incorrect code.

FLOW 2 : 
//on_receiver_recon
counterparty_recon_status  is having incorrect code.

@amolsgirkar

**Comment by amolsgirkar** [comment]
counterparty_recon_status = "01" -> "Paid", "02" -> "Overpaid", "03" -> "Underpaid", "04" -> "Not paid"

we have summited logs for two flow, 
flow1 is with correct settlement amount, where we have sent counterparty_recon_status = 1
and flow2 is with lesser settlement amount, where we have sent counterparty_recon_status = 3. As per ondc contract we have sent correct code.
Please check and let us know the same.

@RupalSingla

**Comment by Ajit-Grab** [comment]
[ONDC] Orderbook must have 5 orders .
[Grab] Digiledge has not implemented the solution, hence unable to test 
P.S. - Logs of digiledge has been approved for Prod.

FLOW 1 :
//on_receiver_recon
counterparty_recon_status is having incorrect code.

[Grab]: Necessary Rectification Done 

FLOW 2 :
//on_receiver_recon
counterparty_recon_status is having incorrect c

[Grab]: Necessary Rectification Done 

@bluecypher @RupalSingla  @amolsgirkar - Please approve ASAP

**Comment by bluecypher** [comment]
- counterparty_diff_amount/value must be string

@amolsgirkar @Ajit-Grab

**Comment by Ajit-Grab** [comment]
@bluecypher @RupalSingla  we have resubmitted - Please check

**Comment by amolsgirkar** [comment]
@bluecypher @RupalSingla we have resubmitted the logs, please check.
FYI @Ajit-Grab

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@Ajit-Grab @amolsgirkar
