### ISSUE TITLE
Digiit LSP (RSF) - compliance checks

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#741]
**/on_receiver_recon**
- context/timestamp can't be earlier than /receiver_recon timestamp
- context/message_id should be the same
- invalid value of context/ttl
- order_recon_status should be "02"

@vignesh-arvind

**Comment by bluecypher** [comment]
@vignesh-arvind, buyer app finder fee is deducted by the collector; How is this processed at your end?

**Comment by vignesh-arvind** [comment]
1. We have stored the order details with buyer finder in our platform accounts ledger book
2. we verify the buyer app deducted buyer finder fee against ledger book
3. if the value is same then we accept the payment
4. if the value is not same, we will initiate correction flow

@bluecypher Kindly let me know if any further details are required.

**Comment by bluecypher** [comment]
@vignesh-arvind, buyer finder fee is not applicable in case of Logistics txn. Are you still allowing inapplicable deductions?

**Comment by vignesh-arvind** [comment]
@bluecypher  sorry for the miscommunication, for Logistics we have submitted separately, we thought the above comments are for retail. 
Kindly review the below for Logistics RSF
https://github.com/ONDC-Official/v1.1.0-logs/pull/768

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0.

@vignesh-arvind
