### ISSUE TITLE
eSamudaay SNP (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#742]
**/on_receiver_recon**
- context/timestamp can't be earlier than /receiver_recon timestamp
- receiver_app_id mismatches with context/bpp_id

@Namratha102000

**Comment by Namratha102000** [comment]
@bluecypher Hi I have raised a PR with corrections

**Comment by Namratha102000** [comment]
Hi please review this

**Comment by bluecypher** [comment]
- Invalid /receiver_recon Payload; schema issue: /message is missing

@Namratha102000, please test with [mock server utility](https://github.com/ONDC-Official/mock-server-utility) to avoid counterparty related issues.

**Comment by developers-esamudaay** [comment]
@bluecypher There was a error in logs extraction at our end. I printed the payload directly, hence the message/orderbook/orders path was missing. Will resubmit with the proper recon request again!

**Comment by bluecypher** [comment]
orderbook timestamps and "@ondc/org/buyer_app_finder_fee_type" enum related issues in /receiver_recon.

@developers-esamudaay, proper checks and balances must be in place.

**Comment by bluecypher** [comment]
Logs approved for RSF v1.0.0, subject to above validations and fixes.

@Namratha102000  @developers-esamudaay
