### ISSUE TITLE
Mystore buyer app - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#75]
1. /init:
- address.locality is mandatory attr key;
- billing.created_at, billing.updated_at is mandatory;
- fulfillment.end.location.gps has changed between search & init. Why was /select not called? This is required as the quote is frozen in /on_select and can't change in /on_init;
2. /confirm:
- address.locality is mandatory attr key;
- order.updated_at is mandatory;
- fulfillment.end.person.name is mandatory;
- in payment block:
- buyer finder fee type is "percent" (lowercase p);
- withholding amt / return window / settlement basis / settlement window are now deprecated;
3. No APIs for /cancel, /update, /status?

**Comment by BLR-0118** [comment]
@mystore-in

**Comment by BLR-0118** [comment]
1. /search & /select have the same fulfillment end location gps coordinates. However, this changes in /init. Whenever, the fulfillment end location changes, /select should be called again so that delivery charges are accurate in /on_select;
2. /init:
- billing.created_at & billing.updated_at should match Context.timestamp;
3. /confirm:
- billing.created_at & billing.updated_at missing;

**Comment by BLR-0118** [comment]
@mystore-in

**Comment by mystore-in** [comment]
1. /search & /select have the same fulfillment end location gps coordinates. However, this changes in /init. Whenever, the fulfillment end location changes, /select should be called again so that delivery charges are accurate in /on_select;

please discuss the above issue with rajiv

**Comment by BLR-0118** [comment]
@mystore-in

**Comment by manusis** [comment]
@BLR-0118 The team will implement the /select before /init if the gps coordinates has changed. It is slightly bigger task at our end as we support multi seller cart so might take 1-2 days. 

Also as discussed, the search and select are independent calls in our case so timestamp might be different. We can resubmit the logs for search and select if required.

**Comment by manusis** [comment]
@BLR-0118 Both changes were made. We are reusing the same transaction id and making the /select call again before the init.

**Comment by BLR-0118** [comment]
closing this with the assumption that the above changes have been made. Will reopen if they're not working as expected.
