### ISSUE TITLE
MP2 TSP LSP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.1.0-logs#758]
## Flow 1 and 2

**/confirm**

- fulfillments/0/tags/@ondc/org/order_ready_to_ship must be equal to one of the allowed values (yes,no)
- payment/type mismatches in /payment in /on_init and /confirm (LSP should send NACK)

**/on_confirm**

- tracking is marked false, but later marked true in on_status (should be true if live tracking is enabled)
) 

@mherle

**Comment by abhinavv245** [comment]
## RTO Flow

**on_status (RTO Initiated)**

- for fulfillment type RTO, start/time/timstamp cannot be before on_cancel context/timestamp

@Poornima-Aithal @mherle

**Comment by Poornima-Aithal** [comment]
@abhinavv245 Fixed the above issue and created a new PR. Please review.

**Comment by bluecypher** [comment]
Logs approved for LSP v1.1.0

@Poornima-Aithal @mherle

**Comment by mherle** [comment]
Thanks @bluecypher and @abhinavv245
