### ISSUE TITLE
Adloggs LSP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.1.0-logs#766]
## Order Flow

**/on_init**

- delivery charges should be inclusive of tax in quote/breakup

**/confirm**

- fulfillment/tracking is not required (BAP cannot enable/disable)
- null values to be avoided  (end/location/id)

**/on_status**

- pickup and delivery time range should not change from the one provided in /on_update
- @ondc/org/collection_amount is not required (required for fulfillment/type 'ON-FULFILLMENT')
- pickup time (fulfillments/start/time/timestamp) is not recorded correctly, cannot be before context/timestamp for 'Agent-assigned'

## RTO Flow

- context/timestamp difference between /action and /on_action should be within 1 sec (/on_update)

**/on_status**

- Message ID for /on_status_RTO_Initiated cannot be same as /on_cancel
- Delivery and RTO charges in quote/breakup do not match with the one provided in /on_search
- order will be cancelled first (/on_cancel) and then RTO will be initiated (context/timestamp and start/time/timestamp should be after /on_cancel context/timestamp)
- for fulfillment type RTO, pickup time range end time(fulfillments/start/time/range/end) should not change in RTO Delivered in comparison to the one in RTO Initiated

**Comment by abhinavv245** [comment]
## Order Flow

**/on_init**

- context/timestamp difference between /init and /on_init should be within 1 sec (current diff : 15 sec)

**Comment by bluecypher** [comment]
Logs approved for LSP v1.1.0

Please fix the delayed response related issues.
