### ISSUE TITLE
Growthfalcon IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.1.0-logs#772]
isssue
- The 'updated_at' of message/issue/issue_action/complainant_actions/index[0]/updated_at should be the same as 'message/issue/update_at' in issue

fulfillment:
issue
- The 'updated_at' of message/issue/issue_action/complainant_actions/index[0]/updated_at should be the same as 'message/issue/update_at' in issue

on_issue_status
- Message  ID mismatch in /issue_status and /on_issue_status

@Ubuntu

**Comment by SandeepGF** [comment]
@RupalSingla Have added the fix for message id and created the pull request 
https://github.com/ONDC-Official/v1.1.0-logs/pull/784

**Comment by Rishabh-ondc** [comment]
on_issue_status
- Processing action's updated_at has changed
- Resolution action not shared
- resolution.refund_amount not shared for REFUND resolution

Clarifications
- Hope the on_issue_status API call has been developed as an unsolicited call as well

@SandeepGF

**Comment by SandeepGF** [comment]
@Rishabh-ondc Can you please review and comment?

**Comment by Rishabh-ondc** [comment]
Missed reviewing, will be reviewed in some time.

**Comment by RupalSingla** [comment]
The resolution of 'CANCEL' provided for the complaint may not be appropriate as the order is already completed. Please make sure appropriate resolutions are shared for the complaints received. 

Logs cleared for version 1.0.0

@SandeepGF
