### ISSUE TITLE
ESamudaay (SA) RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.1.0-logs#777]
receiver_recon:
"@ondc/org/buyer_app_finder_fee_type" is having incorrect enum, should be percentage
settlement_timestamp": "2023-11-03 10:09:15 , is in wrong format.

@Namratha102000

**Comment by Namratha102000** [comment]
https://github.com/ONDC-Official/v1.1.0-logs/pull/778 raised PR with fixes @RupalSingla

**Comment by Namratha102000** [comment]
https://github.com/ONDC-Official/v1.1.0-logs/pull/778 raised PR with fixes @RupalSingla please review

**Comment by Namratha102000** [comment]
https://github.com/ONDC-Official/v1.1.0-logs/pull/778 raised PR with fixes @RupalSingla please review

**Comment by Namratha102000** [comment]
https://github.com/ONDC-Official/v1.1.0-logs/pull/778 raised PR with fixes @RupalSingla please review

**Comment by namrathavpatil** [comment]
@RupalSingla Please review this. Its becoming a blocker we have 4 MSN to onboard and this is taking a direct business hit

**Comment by bluecypher** [comment]
**Duplicate issue board**

Refer to the below issue board for the recent trail
#742
