### ISSUE TITLE
ShiSellerApp (RSF) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.1.0-logs#780]
receiver_recon

- buyer_app_finder_fee_type needs to be percentage .
- created_at and updated_at cannot have same timestamp.

@ucansubodh1

**Comment by RupalSingla** [comment]
Flow 1 :
- "order_recon_status" is having wrong value , it needs to be 01 
- "@ondc/org/collected_by_status" is having empty value ..

@ucansubodh1

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0.

@ucansubodh1
