### ISSUE TITLE
LSN - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#8]
Logs with Eunimart
============
1. why the difference in price between /on_search (78) and /on_init (39)?
2. /on_confirm:
- no collection amount was specified in /search, so where is the value in "@ondc/org/collection_amount" coming from?
- order.updated_at should match Context.timestamp;
3. /status:
- Context.action is wrong;
4. /cancel & /on_cancel:
- Context.timestamp for /cancel is after delivery (timestamp for /on_status shows order was delivered earlier). How can cancellation happen after order delivery & how did LSN accept it?

Logs with Gofrugal
============
1. /search - range.start & range.end are invalid;
2. /init:
- start.building & start.locality are mandatory. Why is LSN not validating?
- same issue as 1 above (Eunimart logs)
3. /confirm:
- why is billing.created_at & updated_at updated here? It should have the same timestamp as in /init.
- "@ondc/org/linked_orders".item.quantity.measure.value should be integer;
- order.created_at & updated_at should exactly match Context.timestamp;
4. No /status, /on_status APIs?

**Comment by BLR-0118** [comment]
@dagapurva3 @SherinShafa27 @sridhareunimart

**Comment by sridhareunimart** [comment]
@BLR-0118 is this LSP buyer app comments?

**Comment by SherinShafa27** [comment]
@BLR-0118 for Gofrugal side
1. Fixed
2. We are sending it now. Also for price mismatch is due to loadshare side handled in that way and its happening with ref buyer app/ plotch apps because where we are searching product by location which is entire city location(say:Bangalore) so for that gps getting 78 as dellivery price while init,shipping address will be particular pincode so gps got changed from buyer app hence from logistics getting delivery price as 42. Hence we are sending updated delivery price to buyer app. 
3. fixed
4. we dont have status api.

**Comment by BLR-0118** [comment]
Logs with Gofrugal:

##LSN:
1. /on_search: item.time.timesstamp is invalid key (should be "timestamp" with 1 "s", not 2);
2. /on_init: payment.collected_by should be "BAP" (with prepaid collection by retail buyer app => settled with retail seller app &  post-fulfillment billing by LSP);
3. /on_track:
- tracking.url not provided, hence, status should be inactive;
4. /on_status:
- Context.timestamp same as for /status;
- message_id different from /status?

##Gofrugal:
1. /init - billing.created_at & updated_at should match Context.timestamp for /init;
2. /confirm:
- provider.id is correct in /init but wrong in /confirm;
- fulfillment.start.time.range & fulfillment.end.time.range will be provided by LSP (in /on_confirm or /on_update), not here;
- why did the Context.message_id format suddenly change here?
3. /support, /track, /update,  /status:
- why is the message_id same as in /confirm?
4. /update:
- how can order.state be created here when it was accepted in /on_confirm?

**Comment by BLR-0118** [comment]
@dagapurva3 @SherinShafa27

**Comment by SherinShafa27** [comment]
@BLR-0118 for Gofrugal 2/confirm -  we are sending same provider.id only - "provider": {
        "id": "loadshare@ondc-preprod.loadshare.net" in init and confirm. kindly check


fulfillment.start.time.range & fulfillment.end.time.range will be provided by LSP (in /on_confirm or /on_update), not here - we are not sending the time ranges during confirm. u can check the existing payload uploaded.

why did the Context.message_id format suddenly change here? - no format is same as in all apis.

**Comment by dagapurva3** [comment]
@BLR-0118 for LoadShare Networks

1. Fixed
2. Fixed
3. Fixed
4. Fixed
5. The logs for /cancel are present in the cancel-workflow folder, so kindly check

**Comment by BLR-0118** [comment]
Logs with Gofrugal
============
1. /on_status - only shows "searching for agent". Not clear if the pickup (fulfillment.start.time.timestamp) and delivery time (fulfillment.end.time.timestamp) are provided at pickup & delivery as required in the contract?

**Comment by BLR-0118** [comment]
@dagapurva3 @poornimaaithal

**Comment by dagapurva3** [comment]
@BLR-0118 for LoadShare Networks

1. /on_search: we don't support rto yet, so that's why we are not sending rto quote in the on_search response
2. Updated the logs for /on_status for searching for agent, order picked up and delivered state, please check.

**Comment by BLR-0118** [comment]
@dagapurva3 - was #2 added now? Innobits which tested yesterday said you're not sending start & end timestamps

**Comment by BLR-0118** [comment]
@darshansada604 - pls check with LSN why you weren't getting start timestamps for your testing y'day?

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0

**Comment by dagapurva3** [comment]
@BLR-0118 - no this wasnt added now, we are sending timestamps from earlier only

**Comment by SherinShafa27** [comment]
> # Logs with Gofrugal
> 1. /on_search - no rto quote as per contract?
> 2. /on_status - only shows "searching for agent". Not clear if the pickup (fulfillment.start.time.timestamp) and delivery time (fulfillment.end.time.timestamp) are provided at pickup & delivery as required in the contract?
> 3. remaining logs look ok

@BLR-0118 

1.on_search will be sent from logistics
2.on_status for completed is submitted already.kindly check
