### ISSUE TITLE
Mystore seller app - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#98]
1. Logs need to be submitted separately for each flow as per the test case scenario [here](https://docs.google.com/document/d/1ttixilM-I6dutEdHL10uzqRFd8RcJlEO_9wBUijtdDc/edit);
2. No /on_search?
3. /on_select:
- item_quantity.count is integer;
4. /on_init:
- payment should only have buyer_app_finder_fee_type ("percent"), amount, settlement_details;
5. /on_confirm:
- order.created_at & updated_at is required;
6. /on_status (2):
- pickup time (fulfillment.start.time.timestamp) needs to be provided when order is picked up;
7. /on_status (3):
- pickup time (above) and delivery time (fulfillment.end.time.timestamp) needs to be provided;

**Comment by BLR-0118** [comment]
@mystore-in

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- time.timestamp for "enable" has to match Context.timestamp;
- time.schedule.holidays is mandatory key (can be empty array);
- contact_details_consumer_care should be in this format: "name, email, contactno";
- category_id should be one of the non-deprecated categories in this [list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0);
- same category_id as above should be in serviceability construct definition;
2. /on_init:
- payment should have buyer app finder fee type & amount;
3. /on_status(1):
- delivery time (fulfillment.end.time.timestamp) can't be set when order is picked up;
4. /on_status(2):
- pickup time (fulfillment.start.time.timestamp) should be the same as what was set in /on_status(1);
5. for both (3) & (4) above, order.created_at can't be changed from what was set in confirm but order.updated_at should be updated;

Flow 2 - need sample payload for non-serviceable usecase, /on_cancel;

Flow 4 - no payload for item out of stock;

No /on_update payload in 1 or 3 as per the testcase scenario?

**Comment by BLR-0118** [comment]
@mystore-in

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- timestamp for "enable" has to match Context.timestamp;
- category_id (for item, serviceability) has to be one of the non-deprecated categories from this [list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0);
- this key is invalid:
-             "availibility": {
              "is_open": 1,
              "start_time": "2023-03-15T18:32:00.000Z",
              "end_time": "2023-03-16T16:30:00.000Z"
            }
2. /on_select:
- select has 2 items (not sure what the item without fulfillment_id means??) but on_select has quote for only 1 item;
- total price for the item doesn't match item price * quantity;
3. /on_status_1:
- order.state of packed is invalid;
4. /on_status_2:
- fulfillment.start.contact.phone & email are invalid;
- fulfillment.start.time.timestamp required;
5. No update APIs?

Flow 2
====
1. Non-serviceable flow:
- since fulfillment is non-serviceable, there can't be any fulfillment level charges;

Flow 4
====
1. No item out of stock payload?

**Comment by BLR-0118** [comment]
@mystore-in

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- core_version should be "1.1.0" (for all APIs);
- no formatting in any free text (e.g. bpp/providers.short_desc & long_desc);
- category_id should be one of the non-deprecated categories in this [list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0);
2. /select:
- payload is wrong: buyer app doesn't assign item.fulfillment_id (surprisingly, this is only in your log, not anyone else's);
3. /on_confirm:
- fulfillment.start.location.gps is different from bpp/providers.locations.gp;
4. /on_status_1:
- order.state of "Order picked up" is invalid;
- order.updated_at should be updated whenever any status changes;
5. No /on_update?

Flow 4
====
1. /on_select:
- item "out of stock" payload is invalid (quote.breakup should have the item with item_quantity = 0);
- unit price * qty is not matching total price;

**Comment by mystore-in** [comment]
1. Feedback implemented

2. payload is wrong: buyer app doesn't assign item.fulfillment_id , We are using refrence buyer app 

3. we are not supporting returnable items that's why no on_update

**Comment by BLR-0118** [comment]
@mystore-in

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- item.category_id should be same as category in serviceability definition. Also, item.category_id should be one of the non-deprecated categories in this [list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0);
2. /select:
- item.fulfillment_id showing here is wrong. Only shows up for your logs & no one else's. Why?
3. /on_confirm:
- fulfillment.start.location.descriptor.name should be the store name as defined in /on_search;
- is the confirm & on_confirm flow, as documented [here](https://docs.google.com/document/d/1j3IdjR3rMwNUkZ6eEGfHkC5oNsE8FY0jKfGqF6zbEik/edit), enabled?
4. /on_update has to be supported, irrespective of whether items are returnable or not;

Flow 4
====
1. /on_select:
- total price for either item in quote.breakup is not equal to unit price * qty;

**Comment by BLR-0118** [comment]
@mystore-in

**Comment by BLR-0118** [comment]
Flow 1 point 1 mentioned above not addressed. No point in resubmitting logs without fixing the issues

**Comment by mystore-in** [comment]
We have resolved that category_id issue and regarding /select there is no issue from our and also please give feedback for all the issue so that we fix all the issues and then submit the logs.

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- "@ondc/org/mandatory_reqs_veggies_fruits"."net_quantity" is string & includes value + UOM (as per contract);
2. /on_update:
- message_id should be same as /update;
- quote.breakup should have the item that was returned with item_quantity = 0;
- no interim states for update (like return initiated, return picked, etc)?

**Comment by BLR-0118** [comment]
pls resubmit logs for flow 1
@mystore-in

**Comment by mystore-in** [comment]
@BLR-0118 can you please review the logs we have resubmitted the updated flow of logs.

**Comment by BLR-0118** [comment]
1. item.fulfillment_id is not valid in /select and item.location_id isn't valid in /on_select;
2. /on_confirm:
- order.updated_at should be updated to Context.timestamp;
3. /on_update:
- should show the complete order trail, i.e. all items in the order & not just the item being returned;
- all amounts ("value") should be string but in this case, some are integer & others string;

**Comment by BLR-0118** [comment]
@mystore-in

**Comment by mystore-in** [comment]
@BLR-0118 Logs are resubmitted plz review there's no issue from our end for select fulfullment_id, Please check all except this

**Comment by BLR-0118** [comment]
1. /on_search:
- item.category_id is fruits and vegetables but serviceability category is packaged foods. what does this mean?
2. /select call is invalid as it includes fulfillment id assigned to item. This should be rejected by seller app. How did this get processed?
3. /on_update:
- quote.breakup.item_quantity.count should be integer, not string (one is string, others are integers)

**Comment by BLR-0118** [comment]
@mystore-in

**Comment by mystore-in** [comment]
@BLR-0118 Logs resubmitted , Select call fulfillment_id issue resolved now and feedback implemented

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0
@mystore-in
